### ISSUE TITLE
Change target of FAQs displayed in app to coronawarn.app//faq/ which is under project control

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-documentation#303] opened 2020-06-18 18:12 UTC
Currently, the target of the FAQ link in the apps is the Bundesregierung's FAQs at: https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392

I consider this subideal, because this page is:
- noisy
- not very well designed
- not under direct project control
- doesn't include the detail of the project FAQs
- doesn't answer many important questions

It would be better, if the FAQ link in the apps targeted the project website FAQs at coronawarn.app/en/faq/ (and German equivalent). These FAQs are cleaner, more up to date, under project control etc.

**Comment by jarjarbentley** [comment] 2020-06-18 19:18
Closing as this issue is a duplicate of issue [289](https://github.com/corona-warn-app/cwa-documentation/issues/289)

**Closed by jarjarbentley** 2020-06-18 19:18 UTC

**Comment by corneliusroemer** [comment] 2020-06-18 22:29
This is related to #289 but it's not an exact duplicate. #289 wants to have a ***unified*** FAQ, I ask no such thing. I ask for the Bundesreg FAQ to be replaced as target with the coronawarn.app.

So I kind of disagree with the simple statement "duplicate" - may still make sense to unify but please offer better reasoning in the future.

I add this as an example to my #IssueClosurePolicy list.

**Comment by sventuerpe** [comment] 2020-06-18 23:58
@corneliusroemer Just to clarify: My focus in #289 was on the problem and not so much on any particular solution. 

My reading of the developers’ responses [there](https://github.com/corona-warn-app/cwa-documentation/issues/289#issuecomment-645856960) and here is that they acknowledge the FAQs need improvement and are working to consolidate the FAQs into a new version that will become accessible from the app. The closure of this issue as a duplicate probably means nothing more than that they consider your contribution as pertinent to the same task and try to keep their to-do list tidy. Closure does not imply rejection unless stated otherwise and “duplicate” merely means they are asking you to check progress elsewhere. Perhaps we can just wait and see what they will come up with, and then evaluate their solution.

**Comment by corneliusroemer** [comment] 2020-06-19 02:24
Thanks @sventuerpe for clarifying! Your explanation makes a lot of sense. I may be prejudiced by bad examples of premature closures I've observed in the past here on this project.
