### ISSUE TITLE
Using the app on two different devices

### ISSUE THREAD

**Issue by KayTeabag** [corona-warn-app/cwa-documentation#204] opened 2020-06-06 19:50 UTC
**What is missing**
Use the app on different devices and have warnings appear on both/send test results from both.

**Why should it be included**
Some people using two or more different devices at different times (such as private and business phones). They might not have each device on them at all times and might miss a warning, or not be able to send a positive test result. 

**Suggested change**
- Manually transferring tracing data from one device to the other whenever they are switched (QR code)?
- Linking devices to automatically transfer tracing data? 
- Linking all devices to a central email/phone number to receive warnings, and send test results? 
- ?

**Comment by ironjan** [comment] 2020-06-06 20:30
Closely related to #82

**Comment by SebastianWolf-SAP** [comment] 2020-06-06 20:35
Dear @KayTeabag,

this is a duplicate of #82 and #171 - as a consequence we will close this issue. The use of multiple devices is currently out of scope. Please see the discussion in #82 for details and also notable aspects concerning this topic.

Thank you for your understanding.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Closed by SebastianWolf-SAP** 2020-06-06 20:35 UTC
