### ISSUE TITLE
Search optimisation app stores 

### ISSUE THREAD

**Issue by benekuehn** [corona-warn-app/cwa-documentation#252] opened 2020-06-16 08:18 UTC
## Where to find the issue
It is very hard to find the app in the app stores, I tried multiple queries and only one result in the official german corona warn app. I was made aware of this via a linkedin discussion here: https://www.linkedin.com/feed/update/urn:li:activity:6678560459697876992/?commentUrn=urn%3Ali%3Acomment%3A(ugcPost%3A6678559715779325952%2C6678563169922768896)&replyUrn=urn%3Ali%3Acomment%3A(ugcPost%3A6678559715779325952%2C6678568843515850752)

![IMG_2374](https://user-images.githubusercontent.com/41262108/84749565-6fa3b900-afba-11ea-8f7c-39ee9972207c.PNG)
![IMG_2375](https://user-images.githubusercontent.com/41262108/84749570-70d4e600-afba-11ea-811f-4e9afff07bd3.PNG)
![IMG_2376](https://user-images.githubusercontent.com/41262108/84749574-73374000-afba-11ea-803a-b87d2c363bb1.PNG)
![IMG_2377](https://user-images.githubusercontent.com/41262108/84749589-76323080-afba-11ea-9325-e2773328f721.PNG)
![IMG_2378](https://user-images.githubusercontent.com/41262108/84749604-78948a80-afba-11ea-8f8b-6f5c31284d64.PNG)
![IMG_2379](https://user-images.githubusercontent.com/41262108/84749612-7a5e4e00-afba-11ea-8f52-3249591a5da5.PNG)
![IMG_2380](https://user-images.githubusercontent.com/41262108/84749615-7cc0a800-afba-11ea-8b5c-e36fb8591f67.PNG)

## Suggested change
Make sure that many people find the app. Maybe talk to Apple (and Google) to get it feature on today page of app store?

**Comment by nerdworldDE** [comment] 2020-06-16 09:12
I experienced the same issue, when i searched for "Corona" in Googles Play store and couldn't find the app at all. I had to search for it via Google.

**Comment by christophriepe** [comment] 2020-06-16 09:37
1. Hier könnte man den Antrag einreichen und damit die App im Heute Tab des AppStores anzeigen lassen. Würde die Anzahl der aktiven Geräte erhöhen, weil man nicht nur über die Suche die App findet.
https://developer.apple.com/contact/app-store/promote/

2. Und zu den Problemen bei der Suche, die App ist noch keinen Tag online und wird daher in der Suche noch nicht so hoch geranked. Die App hat aber jetzt schon 230 Bewertungen (4,8 Sterne). Spätestens in nen paar Tagen ist die wahrscheinlich Nr. 1 bei vielen Keywords.

**Comment by mynchau** [comment] 2020-06-16 09:41
This issue seems to be a duplicate of this one: https://github.com/corona-warn-app/cwa-app-android/issues/474
Let's keep #474 open until the issue is fixed.

**Closed by mynchau** 2020-06-16 09:41 UTC
Labels: bug, documentation

**Comment by sunilgknair051** [comment] 2020-06-17 09:29
Seems to work now. Tried it on few other devices and looks like sometimes I had to type in the "-" between the words. But, it is findable now!

**Comment by benekuehn** [comment] 2020-06-17 12:13
![image](https://user-images.githubusercontent.com/41262108/84896745-bb329180-b0a4-11ea-8f9e-f0da3258c947.png)
Just saw that it’s even featured in today! 👏🏻💪🏼
