### ISSUE TITLE
Correct number of phone text below fig. 7

### ISSUE THREAD

**Issue by Holger-Peine** [corona-warn-app/cwa-documentation#188] opened 2020-06-04 14:14 UTC
## Where to find the issue
In the first and second line of the paragraph below fig. 7

## Describe the issue
The text erroneously says "the app randomly submits requests to the Corona-Warn-App Server (represented in Figure 7 by Phone 2)", while fig. 7 (swim lanes "Phone 2" and "Phone N") shows the phone sumitting that dummy check data to be "Phone N", not "Phone 2".

## Suggested change
Rephrase the text quoted above as "... (represented in Figure 7 by Phone N)".

**Comment by SebastianWolf-SAP** [comment] 2020-06-04 14:58
The text which you mention refers to the upload of dummy diagnosis keys. This procedure is represented by "Phone 2" in figure 7. 

![image](https://user-images.githubusercontent.com/46522656/83772923-35feb400-a684-11ea-806c-1105ffc610fa.png)

I'm therefore unable to reproduce this issue and close it. In case you see it differently, please let us know, we can reopen it again.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Closed by SebastianWolf-SAP** 2020-06-04 14:58 UTC
Labels: documentation, not reproducible
