### ISSUE TITLE
Number of days since last risk-encounter may be not correct on the "increased risk" card

### ISSUE THREAD

**Issue by kbobrowski** [corona-warn-app/cwa-documentation#422] opened 2020-09-05 19:25 UTC
## Where to find the issue

Increased-risk card (on Android, not sure about the behavior on iOS, but possibly it affects both apps)

## Describe the issue

When there is increased risk, "X days since last risk-encounter" is displayed. This information may be not correct, since number of days since **any** encounter will be displayed there, not necessarily number of days since high-risk one.

As an example, if a user had high-risk encounter 5 days ago, and then low-risk 2 days ago (can be even single ping with very weak signal), then it will result in red "increased risk" card with "2 days since last risk-encounter".

## Suggested change

Use `ExposureInformation` (on Android) to get proper date of high-risk encounter, or switch to v1.5 API and correctly infer information from `Exposure Windows`

---
Internal Tracking ID: EXPOSUREAPP-2961

**Comment by GPclips** [comment] 2020-09-30 05:53
Hello @kbobrowski,

I have contacted the development team. Thanks for letting us know, we will inform you as soon as possible about a possible fix.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by rsplaul** [comment] 2020-10-04 20:41
This also affects iOS. Ideas for possible UI fixes in https://github.com/corona-warn-app/cwa-app-ios/issues/1287.

**Comment by Ein-Tim** [comment] 2020-11-02 08:42
@GPclips 
Any update when this will be fixed?

**Comment by webermike** [comment] 2020-11-05 19:51
Please show Date and Time of later on announced risk contacts, even if this leads to still having a green status.

As such contacts might occur only at shopping or eating in a restaurant, one can reconstruct with Date and Time where one habe been and if shopping or queuing anywhere is the risk reason.

This would enhance the analyse and discussion and avoiding of behavior in the future much, when it ia shown if the risk contact was at 8:00 in the bus ir at 12:00 in the McDonalds restaurant or at work at 10:00 o'clock at a certain date/day.

so it is not about "10 days ago" but about exact time and day.

Thanks for implementing that local showup fast.

**Comment by Ein-Tim** [comment] 2020-11-22 10:33
This will be solved with the 1.8.0 release (https://github.com/corona-warn-app/cwa-app-ios/pull/1550)

**Comment by Ein-Tim** [comment] 2020-12-16 18:28
Should be fixed with 1.9 release

**Comment by MikeMcC399** [comment] 2020-12-29 10:51
@kbobrowski 
Can this issue be closed now?

CWA 1.9 provided a major rework in this area https://www.coronawarn.app/en/blog/2020-12-16-corona-warn-app-version-1-9/ including the migration to v2 GAEN.

**Comment by dsarkar** [comment] 2020-12-30 11:30
Dear @kbobrowski, @Ein-Tim, @MikeMcC399, @webermike, @rsplaul, and community,

Thanks for all the contribution. We will close this issue now as suggested, the issue is considered resolved. Best regards, DS

---
Corona-Warn-App Open Source Team

**Closed** 2020-12-30 11:32 UTC
Labels: bug, documentation, mirrored-to-jira
