### ISSUE TITLE
List of supported devices

### ISSUE THREAD

**Issue by ecmjohnson** [corona-warn-app/cwa-documentation#346] opened 2020-06-27 10:16 UTC
It appears that there are limitations based on device and I am unable to find any list of supported devices to know if this is correct or not. This may be related to my Google Play store location being Canada, but the message shown below clearly communicates that the Google Pixel 3 is not supported. I am unable to reasonably find information pertaining to supported devices (other than Android 6 OS dependency) that might explain why I receive this message when trying to install the app (I also can't see it when searching on my device's Google Play for this reason; the below screenshot is from a browser).

![cwa_google_pixel3](https://user-images.githubusercontent.com/6766142/85919852-3ba87d80-b86f-11ea-9352-28b7f8c3d5ff.png)

**Comment by ironjan** [comment] 2020-06-27 11:28
"incompatible device" in "Play Store speak" means one or more of
1. the device does not fulfill the requirements (hardware, OS version, ...)
2. the device was explicitely excluded 
3. your Play Store is "in the wrong country"

(1) and (2) can be ruled out very safely. I'm running the app on the Google Pixel 3a which is a low-budget version of Pixel 3 and a manual exclusion of the Pixel 3 does not make much sense, despite technically possible.

Consequently, the cause of "incompatible" device is the wrong Play Store language/payment setting. You may want to head over to https://github.com/corona-warn-app/cwa-wishlist/issues/38 and cast a vote to support the Canadian Play Store.

**Comment by christianneu** [comment] 2020-06-27 13:44
Dear @ecmjohnson,

The reason for the issue is that you are using Google Play store Canada which is currently not supported.

Our FAQ states the following:

After a detailed examination of the situation it was determined that for legal reasons any publication of the Corona-Warn-App in App Stores outside of Germany is currently only possible after a case-by-case assessment. Legal consultations have shown that in the case of publication in international App Stores, the law of the respective country must be considered and applied to the Corona-Warn-App. This applies in particular to data protection, any necessary claims for information by local authorities and other contractual and consumer protection regulations.

The Robert Koch-Institute as publisher of the app will trigger this check for the respective countries and release the app after successful legal examination. In a first step, the RKI will release the app for some European countries. These are: Netherlands, Belgium, Luxembourg, France, Austria, Czech Republic, Poland, Denmark, Romania and Bulgaria. It may still take a few hours to a few days until the app is available for the individual countries. We kindly ask you for your patience.

More countries are currently being checked and will be released in the App Stores step by step. The Robert Koch-Institute asks for your understanding that it cannot provide any information on specific countries and the status of their release during the ongoing review process.

(https://www.coronawarn.app/en/faq/#international)

Please see also https://github.com/corona-warn-app/cwa-app-android/issues/478

Best Regards
CN
Corona Warn-App Open Source Team

**Closed by christianneu** 2020-06-27 13:44 UTC
Labels: question
