### ISSUE TITLE
Android app screenshot not allowed

### ISSUE THREAD

**Issue by mrascher-cosee** [corona-warn-app/cwa-documentation#283] opened 2020-06-17 12:52 UTC
## Describe the issue
Why doesn't the app let me take screenshots?
Is there a reason for this?

**Comment by tkowark** [comment] 2020-06-17 12:58
This is a duplicate of corona-warn-app/cwa-app-android#516. As it only affects the android app, an answer will be provided there.

**Closed by tkowark** 2020-06-17 12:58 UTC
Labels: bug, documentation
