### ISSUE TITLE
Missing code

### ISSUE THREAD

**Issue by sr-verde** [corona-warn-app/cwa-documentation#42] opened 2020-05-14 08:20 UTC
Hey devs,
I cannot see a single line of code in any repository. Did I missed something, are you developing in internal repositories (shouldn't it be Open Source and therefore developed in public repos?), or is there not a single line written yet?

Best wishes

**Comment by kiliankoe** [comment] 2020-05-14 08:25
This is a dupe of #26.

**Comment by sr-verde** [comment] 2020-05-14 08:29
#26 does not answer all my questions, does it? Are you developing in internal repositories?

**Comment by TomTeeJay** [comment] 2020-05-14 08:45
I second this, when developed in closed repos I am afraid that we won't see all corrctions. commits and ideas behind functions. From a software developers point of view it is crucial to see how a function was developed than to rather see just the result. Compare it with a problem in math. 

The way how somebody solved a problem, the route to a solution is more interesting than the simple result. I am afraid we will get a huge chunk of code with malicious intent.

**Comment by AdrianVollmer** [comment] 2020-05-14 08:55
> Did I missed something

Did you read the name and the description of this repository? That should clear things up.

**Comment by mynchau** [comment] 2020-05-14 08:59
The source code will be available soon.

**Closed by mynchau** 2020-05-14 08:59 UTC

**Comment by corneliusroemer** [comment] 2020-05-14 09:02
I'm pretty sure the answer is: development happens in internal repository.

**Comment by sr-verde** [comment] 2020-05-14 09:04
But why is it not public? I your documents you speak of trust. Doesn't go together with developing internally.

**Comment by s-martin** [comment] 2020-05-14 09:32
> But why is it not public? I your documents you speak of trust. Doesn't go together with developing internally.

As mentioned here and elsewhere, not public YET.

**Comment by sr-verde** [comment] 2020-05-14 09:37
I cannot see any reason for that YET? But of course - there may exist some good ones. In the first place and IMHO, Open Source and (still) internal developing does not match. But if I am wrong, do not hesitate to contradict me.

**Comment by kiliankoe** [comment] 2020-05-14 10:11
As fantastic as open beginning with the initial commit would be, this repo here and its issues/PRs show how every commit would be picked apart by endless discussion. It will probably be far more productive to develop something close to a working prototype and then continue development in the open, with architecture and design decisions already in place.

**Comment by SebastianWolf-SAP** [comment] 2020-05-14 10:40
Please understand that we can't comment further on this topic. You have the clear commitment by several parties that the source code will be free and open source. I would simply ask you to be a bit patient on the question when this actually happens. In the end, we can all give the architects and developers a chance to implement a solid foundation which can be built on. @kiliankoe already mentioned how such a model looks like.
