### ISSUE TITLE
Use correct notation of abbreviations in German translation

### ISSUE THREAD

**Issue by UweKeim** [corona-warn-app/cwa-documentation#648] opened 2021-06-25 17:00 UTC
## Current Implementation

I've seen German texts in the app that contains occurrences of "z.B." written. I.e. without a blank between "z." and "B.".

([Example of where I found it](https://github.com/corona-warn-app/cwa-app-ios/blob/f5abe55fb88387cc9cc5426ec3f6fbfb8aae8866/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L1002))

## Suggested Enhancement

In German the correct notation is "z. B.". I.e. with a blank between "z." and "B.".

My suggestion is to replace all occurrences of "z.B." or "Z.B." by their correct notations "z. B." or "Z. B.".

Also, other abbreviations like "u.a." (correct: "u. a.") might as well be written incorrectly, although I've not discovered them yet.

See also _[DIN 5008, Abkürzungen](https://de.wikipedia.org/wiki/DIN_5008#Abk%C3%BCrzungen_(Abschnitt_4.5))_ on Wikipedia. They suggest to add a _[Geschütztes Leerzeichen](https://de.wikipedia.org/wiki/Gesch%C3%BCtztes_Leerzeichen)_ instead of a normal blank.

## Expected Benefits

The app looks more professional if correct writing and spelling is being used.

---
Internal Tracking ID: [EXPOSUREAPP-8120](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8120)

**Comment by MikeMcC399** [comment] 2021-06-28 07:58
I submitted a related PR https://github.com/corona-warn-app/cwa-website/pull/1435 to fix this issue with FAQs on https://www.coronawarn.app/de/faq/. (The PR does not address any code in the apps though, nor in the [Privacy Notice](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-de.pdf).)

**Comment by dsarkar** [comment] 2021-06-28 08:55
@MikeMcC399 Thanks. PR merged.

**Comment by dsarkar** [comment] 2021-07-02 10:49
FYI PR Android https://github.com/corona-warn-app/cwa-app-android/pull/3610

**Comment by MikeMcC399** [comment] 2021-08-21 10:09
@dsarkar 
In the latest Android branch [release/2.9.x ](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.9.x) there are still occurrences of German abbreviations without a space:

for example: `z.B.` / `d.h.` in the files:
https://github.com/corona-warn-app/cwa-app-android/blob/release/2.9.x/Corona-Warn-App/src/main/res/values-de/strings.xml
https://github.com/corona-warn-app/cwa-app-android/blob/release/2.9.x/Corona-Warn-App/src/main/assets/terms_de.html
https://github.com/corona-warn-app/cwa-app-android/blob/release/2.9.x/Corona-Warn-App/src/main/res/values-de/green_certificate_strings.xml

This includes the `z.B.` mentioned by @Ein-Tim  in https://github.com/corona-warn-app/cwa-documentation/issues/648#issuecomment-868962616 which referred to 
`<string name="general_notification_channel_description">"Erinnerungen, Hinweise und allgemeine Benachrichtigungen, z.B. zu Ihrem Risikostatus."</string> and this text has not been changed in 
https://github.com/corona-warn-app/cwa-app-android/blob/5cbfb0e1d9e065baa835c5c3f86605ef8e88118d/Corona-Warn-App/src/main/res/values-de/strings.xml#L32-L33.

So, probably the 2.5 fix label should be removed, since the issue wasn't completely fixed in the 2.5 release.

**Comment by MikeMcC399** [comment] 2021-11-23 09:54
@dsarkar

This cosmetic issue for the display of abbreviations in the app remains unresolved in the Android app [release/2.15.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.15.x) branch. The app does not conform to  [DIN 5008](https://de.wikipedia.org/wiki/DIN_5008#Abk%C3%BCrzungen_(Abschnitt_4.5)).

For instance `z.B.` (without space) is still written in several places:

![image](https://user-images.githubusercontent.com/66998419/143002720-c6687760-a2a3-4e0c-8f24-7c9cd4d73edf.png)

Also `d.h.` (without space) can be found in src/main/res/values-de/strings.xml.

So the comment from August 2021 https://github.com/corona-warn-app/cwa-documentation/issues/648#issuecomment-903094051 still applies and the fix label 2.5 is not correctly used if this is meant to imply that the issue was completely addressed in version 2.5.


## Reference [DIN 5008](https://de.wikipedia.org/wiki/DIN_5008#Abk%C3%BCrzungen_(Abschnitt_4.5)) 

**Abkürzungen (Abschnitt 4.5)**

In Abkürzungen aus mehreren Buchstaben, die jeweils einen Punkt haben und für ein Wort stehen, ist zwischen den abgekürzten Wörtern jeweils ein Leerzeichen zu setzen: <i>a.&#8239;a.&#8239;O., d.&#8239;h., v.&#8239;l.&#8239;n.&#8239;r., z.&#8239;B.</i> usw. Um einen unerwünschten Zeilenumbruch innerhalb der Abkürzung zu vermeiden, sollte ein [Geschütztes Leerzeichen](https://de.wikipedia.org/wiki/Gesch%C3%BCtztes_Leerzeichen) verwendet werden.

Abkürzungen, die wie selbstständige Wörter oder buchstäblich gesprochen werden, sind ohne Punkt und in sich ohne Leerzeichen zu schreiben. Beispiele: UNICEF, Kfz

**Comment by dsarkar** [comment] 2021-11-23 10:16
@MikeMcC399 Thanks for pointing this out. I will reopen the internal ticket and forward your feedback.

**Comment by MikeMcC399** [comment] 2021-11-23 10:19
Good morning @dsarkar!
Thank you! This is low priority and I'm just going through some older open issues at the moment.

**Comment by MikeMcC399** [comment] 2022-02-15 15:43
@dsarkar 
This issue still has the [Label Fix 2.5](https://github.com/corona-warn-app/cwa-documentation/labels/Fix%202.5) applied to it although the issue is not resolved in any release.

Just to give one concrete example of many in the Android [release/2.18.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.18.x) branch:

https://github.com/corona-warn-app/cwa-app-android/blob/2b05003b632499b79d6e27afd8a9f65b80e1a43a/Corona-Warn-App/src/main/res/values-de/strings.xml#L37
    <string name="general_notification_channel_description">"Erinnerungen, Hinweise und allgemeine Benachrichtigungen, z.B. zu Ihrem Risikostatus."</string>

**Comment by dsarkar** [comment] 2022-02-16 12:53
ok, I remove the "Fix 2.5" label. Once it was fixed, we can add two fix labels, since PR were provided at different releases.

**Comment by dsarkar** [comment] 2022-02-16 12:55
@MikeMcC399 Actually it was decides not to fix this.

**Comment by MikeMcC399** [comment] 2022-02-16 13:07
@dsarkar 

Thank you for checking the status. Probably this issue should now be closed like other issues which are using the https://github.com/corona-warn-app/cwa-documentation/labels/wontfix label.

**Comment by Ein-Tim** [comment] 2022-02-16 13:15
@dsarkar 

But aren't there some "fixed" and some "unfixed" parts now?

**Comment by dsarkar** [comment] 2022-02-16 15:21
some yes, some not. Minor issue.

**Comment by dsarkar** [comment] 2022-02-16 15:25
@UweKeim We suggest closing this issue. Not everywhere the correct whitespace was introduced, however, this minor issue will not be further processed.

Thanks for reporting and participating in this project.


Best wishes, DS

---
Corona-Warn-App Open Source Team

**Closed** 2022-02-16 16:44 UTC
Labels: bug, wontfix, mirrored-to-jira
