### ISSUE TITLE
What happens when a user has two phones and do not carry both at all times

### ISSUE THREAD

**Issue by benekuehn** [corona-warn-app/cwa-documentation#171] opened 2020-05-30 07:48 UTC
* Documentation File:
[solution_architecture.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#limitations)
* Line / Paragraph:
>**Retrieval of lab results and verification process**
>The Corona-Warn-App Server uses the TAN to verify the authenticity (Figure 3, steps 13-15) of the submission with the Verification Server. The TAN is consumed by the Verification Server and becomes invalid (Figure 3, step 14)
* Question:
Some people do carry two phones and switch them regularly, eg one work phone one private phone. AFAIK only one TAN comes with the result is invalid after on use, which indeed should be the case. But how can we allow people to mark two phones and their sent IDs as infected with on test result?

**Comment by tklingbeil** [comment] 2020-05-30 08:00
This is a duplicate of #82.

Currently the use of multiple phones is out of scope.

**Comment by SebastianWolf-SAP** [comment] 2020-05-30 08:15
Closing as it's a duplicate.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Closed by SebastianWolf-SAP** 2020-05-30 08:15 UTC
Labels: question
