### ISSUE TITLE
In-App statistics update too late

### ISSUE THREAD

**Issue by whiskey** [corona-warn-app/cwa-documentation#533] opened 2021-02-26 11:53 UTC
**EDIT Corona-Warn-App Open Source Team**
see comment https://github.com/corona-warn-app/cwa-documentation/issues/533#issuecomment-876216994

> **The alternate source of most data is:**
> 
> The Dashboard on https://corona.rki.de/ which covers everything except the 7-Day R Value.
> 
> The "7-Tage-R-Wert" is published on the previous evening in the daily report on https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Gesamt.html and in my experience this is the easiest place to pull this value.
> 
> Otherwise RKI references this value on https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting.html and publishes to https://github.com/robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung/blob/main/Nowcast_R_aktuell.csv. Note that the 7-Day R Value is continually revised, so it may be difficult to follow.
> 

---
**Original post**
---

First the basics:

## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: any
- iOS Version: any
- App Version: any since the statistics

## Describe the bug

The in app statistics are great but updated too slowly. How can it be that DLF announces the latest numbers at 6 in the morning and the app still shows at 08:00 the stats from the previous day? Please update earlier, you have the 'direct line' to the RKI.

## Steps to reproduce the issue

1. Get up early in the morning (yes, this still happens, despite home office)
2. [Listen to the radio](https://www.deutschlandfunk.de/unsere-live-streams.2396.de.html) at 06:00
3. Compare announced numbers to the in-app statistics

## Expected behaviour

Numbers in the app are updated to the latest statistics.

## Possible Fix

Only Server sided. No need to adjust the app code.

## Additional context

n/a

---
Related: https://github.com/corona-warn-app/cwa-documentation/issues/532
Internal Tracking ID: [EXPOSUREAPP-5448](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5448)

**Comment by dsarkar** [comment] 2021-02-27 17:11
@whiskey @Ein-Tim Moved to documentation repo. The server repo is not related to RKI statistical data.

**Comment by dsarkar** [comment] 2021-02-27 17:22
@whiskey  @Ein-Tim Thanks. Internal Tracking ID: [EXPOSUREAPP-5445](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5445)

**Comment by MikeMcC399** [comment] 2021-02-27 17:30
> The server repo is not related to RKI statistical data.

See https://github.com/corona-warn-app/cwa-server/issues/1223 where it was confirmed that the cwa-server just has a reformatting and pass-through function as far as RKI infection statistics is concerned.

This repository (https://github.com/corona-warn-app/cwa-documentation) is the best one for functional problems affecting both the iOS and the Android app.

**Comment by dsarkar** [comment] 2021-03-01 07:17
New Internal Tracking ID: [EXPOSUREAPP-5448](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5448)

**Comment by GisoSchroederSAP** [comment] 2021-03-02 09:01
All,
regarding the "too late" question: 
The consolidation cycle of the current day's in-app statistics on server side starts at 0:10 a.m. Multiple (at least 4) data sources are examined and reviewed.
Not before 05:30 a.m. daily, the "ESRI dashboard" will be updated. Once this task is performed, the data analysts review and validate the different data streams, all data are consolidated, processed, and condensed to the statistics later displayed in the CWA - data quality and consistency is crucial before releasing the data records.

Unfortunately, there is no real "latest time to expect statistics" - at least not of my knowledge.
However, when the internal alerting for any delay or service outage on the server side gets triggered, the data analysts and operational experts will jump in to analyze the root cause and fix it accordingly - if necessary, even with manual intervention. Once finished, the new statistical records will be made available to the app.

So, yes, as multiple data sources are combined and those are not always available/up-to-date at the same time with the same level of data quality, the complexity for the CWA-feeding background process is much higher than scanning one single data pot. Subsequently, the required effort for presentation with respect to time and data quality is higher. 

As those in-app statistics shall support users and help them adjust their own behavior accordingly, we consider data accuracy and consistency is key. Still, we are working on continuous improvements and acceleration of the process.

**Comment by MikeMcC399** [comment] 2021-03-03 07:23
@GisoSchroederSAP 
Thank you for the insight into the process!

Today, Wednesday, March 3, 2021 at 08:00 all RKI statistics values shown by the (Android) app are consistent and up-to-date with other RKI information sources available online ([Dashboard](https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4) and [Fallzahlen](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html)). 👍

**Comment by MikeMcC399** [comment] 2021-03-18 15:28
Today, Thursday, March 18, 2021 16:20 all values in the app have been updated **except** the 7-Day Incidence, which is still showing the value 86.2: the same as it showed yesterday. The new value of  90 was published by RKI to [Fallzahlen.html](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html) this morning at 09:40 and the value of 90.4 is also shown in RKI's [Fallzahlen_Kum_Tab.xlsx](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab.xlsx) Excel file (in cell BL_7-Tage-Inzidenz'!LG20).

So I'm wondering what happened to the data feed for the 7-Day Incidence to the CWA app which I would expect to show 90.4 right now, instead of 86.2.

**Comment by dsarkar** [comment] 2021-03-18 15:40
@MikeMcC399 Indeed, the values were updated late today. Will try to get info about the 90.4 / 86.2 discrepancy.

**Comment by GisoSchroederSAP** [comment] 2021-03-18 19:37
I can confirm: 8:35 p.m. The value of the 7-day Incidence is still not yet updated.
So, I'm going to force the data analysts one more time...

**Comment by GisoSchroederSAP** [comment] 2021-03-18 19:51
Update: I'm going to ask tomorrow morning, if there is a way to indicate early, when there is an issue that prevents an in-time update of the statistics. Someone must be able to have transparency on the process.

**Comment by MikeMcC399** [comment] 2021-03-18 19:55
@GisoSchroederSAP 
It's strange that only one value is missing. Thank you for following up!

Even the official PDF reported which is published every evening has the value 90.
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Maerz_2021/2021-03-18-de.pdf

![image](https://user-images.githubusercontent.com/66998419/111689359-37bcf100-882c-11eb-8662-82ee2c563324.png)

**Comment by GisoSchroederSAP** [comment] 2021-03-18 21:21
Let me share one more fact: 
I already mentioned, those statistics will be consolidated separately based on various different sources, right?
Having this in mind, our implementation works as follows:
- For all tiles, we start in the early morning to collect data from different sources. 
- If those data are available, they will be consolidated.
- If all data for _one_ statistics tile are available, the data will be processed and the validity review happens. 
- If the latest review is successful, the result(s) will be pushed to the server, where the app can them pick up and update the the value(s) on the tile.

There a lot of  "if" conditions, aren't there?
So, if one "if" fails, this respective tile will not updated. 
On the other hand, the process may still succeed for other tiles and the user gets at least, what we have so far.
The alternative would be: Wait until all calculations are finished successfully. But this would mean, either all or none of the tiles get updated. We decided, not to go this path,, though.

Does this help?

**Comment by Ein-Tim** [comment] 2021-03-19 09:32
As of now, all statistics are up to date.

**Comment by MikeMcC399** [comment] 2021-03-19 13:07
@GisoSchroederSAP 
Thank you for explaining about the granularity of the publishing process.

Did you find out why the value 7-day Incidence 90.4 was not published during the working day yesterday, March 18, 2021?

@Ein-Tim 
> As of now, all statistics are up to date.

Agreed. Today, Friday, March 19, 2021, went much more smoothly. 

Today's  7-day Incidence is 95.6 and this is showing in the app. The site [COVID-19: Fallzahlen in Deutschland und weltweit](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html) was updated today at 07:50 and [Robert Koch-Institut: COVID-19 Dashboard](https://www.esri.de/corona) showed today's data even earlier (it is currently showing "Letzte Aktualisierung: 19.03.2021, 09:06 Uhr, although that was not the first update of today).

**Comment by MikeMcC399** [comment] 2021-04-12 17:00
@GisoSchroederSAP 

Did you learn any more about the reasons for past problems?

The data in the app seems to be getting updated reliably the last days. Are you monitoring this automatically?

**Comment by GisoSchroederSAP** [comment] 2021-04-12 17:14
I'm validating the content/values  from time to time, still confident about correctness of the calculation. 
Update: Meanwhile, there was a new technical interface established that allow faster and more often updates on the analytics engine. This would somehow confirm your comment about reliability - and it seems to have a impact to the timing (early update each day) - keep the fingers crossed.
Last update: I documented all statistic tiles and translated them (DE/EN) - these texts are now under review. Once released, we are going to make them available on the FAQ page.

**Comment by MikeMcC399** [comment] 2021-07-07 19:50
@GisoSchroederSAP 

The statistics seem to get updated regularly and timely, so perhaps this issue https://github.com/corona-warn-app/cwa-documentation/issues/533 (In-App statistics update too late) can now be closed?

> Last update: I documented all statistic tiles and translated them (DE/EN) - these texts are now under review. Once released, we are going to make them available on the FAQ page.

Is this action still to-do or has it been abandoned.

**Comment by GisoSchroederSAP** [comment] 2021-07-07 23:09
I had another talk with RKI about the translation of statistic tiles (round four)  and hopefully can publish the German version soon.
But certainly, we can close this issue #533.  
Btw, we now get early updates in case the statistics cannot be provided in the early morning. So, we are ahead of the consumers and act timely, which is much easier in communication.

**Comment by Ein-Tim** [comment] 2021-07-08 04:59
Actually, as of now, the statistics in the app were not updated.

**Comment by MikeMcC399** [comment] 2021-07-08 05:54
From my point of view, if the app updates by 08:00 on 95% of days I would be satisfied, however I realize that is just my definition of a Service Level Objective, which may not satisfy other people's expectations.

It is currently 07:53 on Thursday, July 8, 2021 and all four stats tiles have been updated.

**Comment by GisoSchroederSAP** [comment] 2021-07-08 06:42
Yes, confirmed. Today at 7:16 I got notification of a data chain disruption, at 7:52 I got the solution confirmed.
From this point of view I think, we  now have an acceptable working mode.

**Comment by dsarkar** [comment] 2021-07-08 07:29
Hi @MikeMcC399 and communty! Shall we close this one, or shall we keep open as a channel for updates by @GisoSchroederSAP regarding temporary "hick-ups" ?

**Comment by MikeMcC399** [comment] 2021-07-08 07:32
@dsarkar 
I vote to close.

**Comment by dsarkar** [comment] 2021-07-08 07:35
Noted. Hereby we close this issue. Will be reopened if necessary. Thanks everybody.

Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment] 2021-07-08 07:53
The alternate source of most data is:

The [Dashboard](https://corona.rki.de/) on https://corona.rki.de/ which covers everything except the 7-Day R Value.

The "7-Tage-R-Wert" is published on the previous evening in the daily report on https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Gesamt.html and in my experience this is the easiest place to pull this value. 

Otherwise RKI references this value on https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting.html and publishes to https://github.com/robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung/blob/main/Nowcast_R_aktuell.csv. Note that the 7-Day R Value is continually revised, so it may be difficult to follow.

**Closed** 2021-07-08 08:35 UTC
Labels: mirrored-to-jira, statistics

**Comment by Ein-Tim** [comment] 2021-07-08 09:24
Reading the OP of @whiskey again, I don't think that's fixed. If the statistics always update at ca. 8:00h, this is 2h later than e.g. DLF announces the latest numbers. Could @GisoSchroederSAP comment if it's impossible for the CWA-Team to also have the figures updated as early as radio stations announce them or if this would theoretically be possible.

**Comment by GisoSchroederSAP** [comment] 2021-07-08 11:48
Just a comment on the comparison with local radio stations and regional newspapers/websites.
Beside the fact those channels provide numbers earlier, there are three major differences:
* Those channels at least partly gather their information from different sources, including RKI, but also from local authorities' publications 
* Subsequently, they may differ in the exact numbers (still reflecting the current trends), and those number are interpreted by the media experts, but not by data analysts
* Those radio stations and channels do not consolidate and verify the validity of numbers (especially with respect to the history) - in contrast, the CWA analytics team, however, runs several  statistical evaluation on the data sets including the historical data sets to ensure precision and consistency. In case, this team discovers irregularities (like today in the early morning), a second batch run starts together with the investigation for the source of deviation (today: one missing data element because of interrupted data transmission). 

This service of collecting, storing, clustering, checking/validating starts at 5 a.m. is usually finished between 6. a.m. and 7 a.m. If not, we become informed and can safely communicate.

Cheers, Giso

**Comment by Ein-Tim** [comment] 2021-07-08 11:54
@GisoSchroederSAP 

Thank you for the clarification. As said, this is fine for me and I appreciate the efforts of the CWA (analytics) team here. Really nice!

Seems like it's okay to have this issue closed.
Have a nice day everyone.
