### ISSUE TITLE
Error 39508 since 2020-08-19

### ISSUE THREAD

**Issue by Matzgitz** [corona-warn-app/cwa-documentation#431] opened 2020-09-26 06:19 UTC
I got the error 39508 since 2020-08-19. Several app updates and OS Updates did not fix the issue. Running Android 10.
![Screenshot_20200926-081541266](https://user-images.githubusercontent.com/33512627/94331890-8487e380-ffd0-11ea-8670-7c9606af9d9b.jpg)

![Screenshot_20200926-081551315](https://user-images.githubusercontent.com/33512627/94331893-89e52e00-ffd0-11ea-8308-e8c2be36efd9.jpg)

Freezing the App (or not opening like explained an FAQ) does not fix the issue.

**Comment by Ein-Tim** [comment] 2020-09-26 07:28
Related: https://github.com/corona-warn-app/cwa-app-android/issues/774

**Comment by daimpi** [comment] 2020-09-26 11:08
@Matzgitz 
You could try what I suggested [here](https://github.com/corona-warn-app/cwa-app-android/issues/1021#issuecomment-695778752).
This issue is a duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/1021, I'd suggest you close it and we move the discussion over there.

**Comment by Matzgitz** [comment] 2020-09-26 14:13
This issue is a duplicate of corona-warn-app/cwa-app-android#1021, we move the discussion over there.

**Closed** 2020-09-26 14:12 UTC
