### ISSUE TITLE
F-Droid support

### ISSUE THREAD

**Issue by codedust** [corona-warn-app/cwa-documentation#6] opened 2020-05-13 08:18 UTC
Many Android users, e.g. those using [LineageOS](https://lineageos.org/) or [Replicant](https://www.replicant.us/), do not use Google Play Services for privacy reasons. In order to achieve broad adoption of the app and enable anyone to use the app it is inevitable to have the possibility to use the app without proprietary Play Services installed.

Please make sure it is possible to compile the app without any non-free dependencies. This would allow the app to be included in [F-Droid](https://f-droid.org/). See F-Droid's [inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/) for details:

> We cannot build apps using Google’s proprietary “play-services”. [...]
> We cannot build apps using proprietary tracking/analytic dependencies like Crashlytics and Firebase. [...]
> We cannot build apps using proprietary ad libraries. [...]
> We cannot build apps requiring Non-Free buildtools, including Oracle’s JDK or some pre-release toolchains. [...]

Thanks in advance!

**Comment by mojoaxel** [comment] 2020-05-13 08:19
duplicate of #5

**Closed** 2020-05-13 08:19 UTC
