### ISSUE TITLE
Ensure privacy by not accessing network resources if not required

### ISSUE THREAD

**Issue by Spacefish** [corona-warn-app/cwa-documentation#24] opened 2020-05-13 16:48 UTC
The documentation as well as the requirements list multiple features like

- pulling of proximity calculation parameters
- content download (help hotline number / informational pages and so on)

which would trigger network requests from the App to backend servers.

This violates the users privacy IMHO as the IP of the user and potentially an user-agent string is transmitted to the backend-servers. If there are special information pages for "infected" or "potentially infected" people and these pages are pulled on demand, this would de-anonymize the users.

Deutsche Telekom is one of the projects stakeholders, as they are a big ISP in germany used by a lot of people, they have the capability without any external control, to de-anonymize users which are their customers. I think this is an issue and should be avoided.

I would suggest that the app does not "pull" or "push" any additional information from an backend.

The only time this is required: If someone is marked "infected" and their token set needs to be uploaded to the Cloud.

"Infected Token download" could be implemented by means of public mirrors by trusted 3rd parties. Validity of the tokenset can be checked by a digital signature. The app should contain a list of public mirrors which are choosen at random on initial application start.

**Comment by egandro** [comment] 2020-05-13 16:54
This was discussed in #13 and somehow "removed" :(

**Comment by tkowark** [comment] 2020-05-13 17:41
Closing this as a duplicate of #13

**Closed by tkowark** 2020-05-13 17:41 UTC
Labels: duplicate
