### ISSUE TITLE
Missing screens on the UI-Screens.md

### ISSUE THREAD

**Issue by kraleva** [corona-warn-app/cwa-documentation#272] opened 2020-06-17 09:29 UTC
## Where to find the issue
The issue can be found in the following[ documentation, wiki-markdown file](https://github.com/corona-warn-app/cwa-documentation/blob/master/ui_screens.md).

## Describe the issue
As i was doing a flow-chart diagram for the project, I noticed that there are screens, which have not been documented by this document. My flowchart can be seen here: 
![flow-chart (1) (2)-Page-1](https://user-images.githubusercontent.com/39501165/84880965-86ffa680-b08d-11ea-9dcf-0bdda7a8955e.png)
What I noticed is that a lot of the TAN/QR screens are not documented at the given markup, which i find problematic.
## Suggested change
Add the screens in the documentation.

---
Internal Tracking ID: EXPOSUREAPP-2962

**Comment by tkowark** [comment] 2020-06-17 09:33
Dear @kraleva this is not a bug, as the UI screens document was intended to mostly give a glimpse into the available screens. I'll add the enhancement label and clarify with the UX team whether more screens can be provided.

**Comment by MikeMcC399** [comment] 2021-03-11 09:53
UI screenshots are now automatically generated for the current release and posted to https://www.coronawarn.app/en/screenshots/ including sections on:

- Test registration & Key sharing
- Test result home

In the issue https://github.com/corona-warn-app/cwa-documentation/issues/508 there is a discussion about whether to keep or replace the original UI screen shots listed in https://github.com/corona-warn-app/cwa-documentation/blob/master/ui_screens.md.

**Comment by MikeMcC399** [comment] 2021-07-07 20:01
This issue can be closed, as the file https://github.com/corona-warn-app/cwa-documentation/blob/master/ui_screens.md now specifically says:

"Here you can find screenshots of some of the features that the Corona-Warn-App offers in the current release: [Take a Look](https://www.coronawarn.app/en/screenshots/). The corresponding German screenshots can be found here: [Machen Sie sich selbst ein Bild](https://www.coronawarn.app/de/screenshots/).

The screenshots shown in the following are outdated."

meaning it is now clearly documented that the file https://github.com/corona-warn-app/cwa-documentation/blob/master/ui_screens.md contains outdated screenshots.

**Comment by dsarkar** [comment] 2021-07-08 06:57
Good morning @MikeMcC399, Thanks for the suggestion. We will close this issue. 


----
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2021-07-08 07:03
@MikeMcC399 Added your comment to the internal ticket.

**Closed** 2021-07-08 07:02 UTC
Labels: UX, documentation, enhancement, mirrored-to-jira
