### ISSUE TITLE
Is it really possible to test the apps? How to become whitelisted?

### ISSUE THREAD

**Issue by gitbrueck** [corona-warn-app/cwa-documentation#214] opened 2020-06-02 06:19 UTC
Known Issue: "The Exposure Notification API is gonna block you from successfully testing the Application unless you are whitelisted inside GMS."

---
Internal Tracking ID: EXPOSUREAPP-2963

**Comment by SebastianWolf-SAP** [comment] 2020-06-09 10:04
Dear colleagues,

as this is a rather generic topic and affects both worlds (iOS and Android), we moved that over to the documentation repository. Please understand that we don't have any updates at this point in time about the enabling of external developers/testers etc. We will update the issue once we have any updates.

If you would like to ease the mocking of the Exposure Notification API for Android (similar to the efforts which have been done on the iOS side), the team will certainly accept contributions. But please use separate issues/pull requests for that and limit discussions here to the original question.

Thanks for your understanding.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by kraleva** [comment] 2020-06-10 09:02
Ich kriege das selbe Error, nur mit dem Unterschied, dass es statusCode=UNKNOWN_ERROR_CODE(39503) ausgibt (Wäre das das gleiche Error?). Ich hab trotzdem es geschafft mit Error-Message Popups es zu starten als Workoaround. Hier könnt ihr auch ein [Video](https://drive.google.com/file/d/1sUy6UvZYV8iBuMNwmLExOTKm1HauT5TW/view?usp=sharing) mit dem Ansichten finden, wenn ihr das Projekt nicht starten könnt.

**Comment by Fabian42** [comment] 2020-06-16 11:28
Obligatory update: The app is now officially available, so you can test it.

**Comment by mynchau** [comment] 2020-06-16 13:28
And since the app is officially available, I'm closing this issue. Thanks everyone for your ongoing contribution! 
Best regards
MC 
Your Corona Warn-App Open Source Team

**Comment by corneliusroemer** [comment] 2020-06-16 18:34
What are you doing @mynchau. This is not how this works. Don't close the issue or I will reopen out of protest.

The app version 1.0 is released. We may still want to test future versions. Also, there's the question of reproducible build. There are lots of reasons why there may still need a need to test the app.

It's maybe not top priority, but the issue is NOT done with.

@SebastianWolf-SAP could you please let @mynchau know about the discussion we've had re no closing issues until they are properly resolved to the satisfaction of the community?

**Comment by SebastianWolf-SAP** [comment] 2020-06-16 19:35
Dear @corneliusroemer,

please treat everybody with politeness and courtesy. I has been a long day for everybody and you can notify @mynchau yourself. I really need to remind you of our [code of conduct](https://github.com/corona-warn-app/cwa-documentation/blob/master/CODE_OF_CONDUCT.md) and we really want to avoid sending out warnings or similar things.

And of course, we will keep this issue open until we have a solution for proper dev/testing.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by corneliusroemer** [comment] 2020-06-16 22:10
@SebastianWolf-SAP Ah here you mentioned the code of conduct for the first time.

What in particular is wrong about my comment? The first version was a bit harsh, I'm sorry for that. But the current version?

It's sometimss frustrating that there seems to be not much appreciation for the work put into these issues when they're closed just like that. We'd had that discussion, but then it happened again

**Comment by kbobrowski** [comment] 2020-07-05 01:11
Anyone can become whitelisted using following project: https://github.com/kbobrowski/en-i13n

The reason for this project is that it's extremely inefficient to try to debug deployed app which is downloaded from the Play Store, as we cannot simply add some more logging / modify code and see what is going on, especially if the issues arise from interaction with EN framework. This is especially visible in Android issues: https://github.com/corona-warn-app/cwa-app-android/issues/774, https://github.com/corona-warn-app/cwa-app-android/issues/737. Using mentioned project anyone can just fork the app code, deploy using e.g. Android Studio and have it working with EN framework.

Extension for (jailbroken) iOS should be possible, depending on the mechanism used to parse signatures of allowed apps. Perhaps only small modification would be needed.

**Comment by francwalter** [comment] 2020-11-21 10:09
I hope this is the right spot to ask: 
ge
Is it possible to test the app in e.g. the Android Studio's AVD or Genymotion (Android Emulator)?

I compiled the actual source from github in my PC (with Windows 10, 64-Bit) in Android Studio (actual version 4.1.1) successfully (no errors with Gradle, a apk was created), then I copied the apk to Genymotion (vs3.1.2) into a virtual Android 10 and tried to install it. Install ran but was not successful (App not installed).

Before searching what was wrong, I thought now, maybe this app is not ment to use just as test or to compile by myself and use it normally.
So here I ask: can I test a self compiled version on a virtual device or even on my phone (productively)?

Thanks for an answer.
Frank

**Comment by ndegendogo** [comment] 2020-11-21 10:30
On  **iOS** a special entitlement (certificate) is required to be able to use the ENF API. For this reason the cwa development team has mocked this API, to allow also community members / the public to compile and run the cwa code.

Not sure if **Google / Android** has similar restrictions ...

**Comment by ndegendogo** [comment] 2020-11-21 10:40
*Disclaimer: I don't know anything about Android development.*

> Genymotion (v3.1.2) into a virtual Android 10

Question: does this environment contain a (current) Google Play services?
Because the Google Exposure Notification Service (ENS) is part of this Google Play.

**Comment by MikeMcC399** [comment] 2020-11-21 12:41
@francwalter 
> can I test a self compiled version on a virtual device or even on my phone (productively)?

In short the answer is **no**, unfortunately.

Let's start with what does work 😄 :
- CWA Android 1.6.1 from Google Play Store running on Android Studio's Pixel 3a emulator configured with Play Store and API 30 (Android 11). The only limitation I found is that there are zero keys recorded when viewed through the Google UI.

Now for what doesn't work. In fact you can often start the app, but after onboarding it gives errors and cannot be used in any meaningful way:
- CWA Android built from github, with same emulator environment as above i.e. Android 11. This gives error 17/39507. See https://github.com/corona-warn-app/cwa-app-android/blob/main/README.md "The Exposure Notification API is going to block you from successfully testing the Application unless you are whitelisted inside GMS; ..."
- CWA Android 1.6.1 downloaded from apkmirror.com and installed on Android Studio's Pixel 3a emulator with Play Store and API 29 (Android 10). This gives error 17/39501. There is no Bluetooth hardware emulation on this emulator.

Finally, this configuration is completely blocked and the app cannot be installed:
- CWA Android 1.6.1 from Google Play Store which blocks it with the message "Your device isn't compatible with this version", presumably again because the Android 10 emulator doesn't have fully emulated Bluetooth capabilities.

Genymotion may have a better Bluetooth environment for Android 10. I don't have any experience with it, I'm afraid.

However the fundamental problem is that Google has restricted the API use
https://developers.google.com/android/exposure-notifications/exposure-notifications-api#gloss_allowlisted.

There are quite a few people in the community who would willingly test beta- or pre-releases. This has not been possible so far unfortunately. There was an update yesterday in https://github.com/corona-warn-app/cwa-wishlist/issues/153#issuecomment-731183577 from the Open Source Team which said that it still isn't possible.

**Comment by mh-** [comment] 2020-11-21 12:50
@kbobrowski shows how GMS can be tricked into working even with your own app here: https://github.com/kbobrowski/en-i13n (requires root)

**Comment by MikeMcC399** [comment] 2020-11-21 15:52
@mh- 
>@kbobrowski shows how GMS can be tricked into working even with your own app here: https://github.com/kbobrowski/en-i13n (requires root)

The instructions in https://github.com/kbobrowski/en-i13n/blob/master/README.md were too complicated for me and I didn't want to have to root a device to try out the app. I'm happy if this is a solution for some people. I was just looking for something much simpler.

**Comment by dsarkar** [comment] 2020-11-22 10:43
Dear community,

We will approach the developers about CWA beta testing by the community. Any further development will be published here.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by yauauau** [comment] 2021-07-14 08:22
Hi[5185693630]()

**Comment by ndegendogo** [comment] 2021-07-15 06:51
@yauauau - I don't quite understand your last comment / link?

**Comment by svengabr** [comment] 2022-06-14 12:47
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Wont Fix`
Status: `Obsolete`

Developer comment:
> App cannot be tested or deployed by community without whitelisting.
> 
> Google is only whitelisting Public Health Authorities

**Closed by svengabr** 2022-06-14 12:47 UTC
Labels: bug, documentation, mirrored-to-jira

**Comment by MikeMcC399** [comment] 2022-06-14 12:56
@svengabr 

I suggest that you also unpin this issue, which currently shows at the top when viewing the issue list
https://github.com/corona-warn-app/cwa-documentation/issues.
