### ISSUE TITLE
Publish app code

### ISSUE THREAD

**Issue by jbxbergdev** [corona-warn-app/cwa-documentation#61] opened 2020-05-15 13:38 UTC
According to media reports, the apps are going to be published soon. The documentation states that the code will be available under the Apache v2 license. It is in public interest that reviewing the code is possible early, ideally before the apps go live. So, the projects source code should be published as soon as possible. 

Until the code gets published, the documentation should elaborate in more detail on when and to what extent the code will be available as open source.

**Comment by niklas2810** [comment] 2020-05-15 13:39
Duplicate of #59

**Comment by jbxbergdev** [comment] 2020-05-15 14:13
May I ask why this and similar issues keep getting closed? It would seem sensible to have an open issue if open sourcing the code is on th road map?

**Comment by s-martin** [comment] 2020-05-15 14:17
Because the project members stated multiple times that the existing code will be published soon and need to be a little patient.
E.g. here https://github.com/corona-warn-app/cwa-documentation/issues/59#issuecomment-629213322 two hours ago

**Comment by jbxbergdev** [comment] 2020-05-15 14:21
Thanks for the reply. You wouldn't have to reply multiple times if you kept one of the issues open, since it's still in progress and so the status would be easily visible to everyone. ;-)

**Comment by tkowark** [comment] 2020-05-15 15:50
Thanks @jbxbergdev and @s-martin for the discussion. Always happy to learn and adapt. We'll reopen this ticket and will only close it, once the first source code is online.

As stated before, this will happen soon.

**Comment by quaddy-services** [comment] 2020-05-15 16:36
As guthub should be the master repository (and not an outdated clone of your internal ones) there is no reason against pushing each development commit here directly...

**Comment by SebastianWolf-SAP** [comment] 2020-05-30 15:33
We just published the last two remaining repositories:
- https://github.com/corona-warn-app/cwa-app-android
- https://github.com/corona-warn-app/cwa-app-ios

Have fun digging through the code, looking forward to your contributions!

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Closed by SebastianWolf-SAP** 2020-05-30 15:33 UTC
Labels: documentation, enhancement, in progress
