### ISSUE TITLE
Contact protocol never checked

### ISSUE THREAD

**Issue by checkfrog** [corona-warn-app/cwa-documentation#324] opened 2020-06-21 07:59 UTC
I installed the iOS app the moment it was available on the app store. Now, more than five days later, it still says in the iOS settings that the contact protocol has never been checked in the last 14 days.
Since location data is not stored, every submitted infection should trigger all devices to be checked, right? That either means that no infection has ever been reported so far or that my iOS implementation is not working.

**Comment by cfritzsche** [comment] 2020-06-21 08:02
So far, no positive keys are available at the server. Partly that is due to a 140 key minimum not yet reached. That’s probably why there are no checks yet. Developers are working on padding missing keys to ensure a timely delivery of keys. https://github.com/corona-warn-app/cwa-documentation/issues/236#issuecomment-647090159  But nobody knows if any key was submitted yet also.

**Comment by tkowark** [comment] 2020-06-21 08:27
Thanks for the answer, @cfritzsche . This is also a duplicate of #311

**Closed by tkowark** 2020-06-21 08:27 UTC
