### ISSUE TITLE
Test result not taken into account for combined status 

### ISSUE THREAD

**Issue by svenfoo** [corona-warn-app/cwa-documentation#825] opened 2022-01-26 15:17 UTC
## Technical details

- Device name: Motorola One
- Android version: 10
- App version: 2.16.2

## Describe the bug

In the certificates view the app displays a combined status. With three vaccinations imported for me into the app, my status is **2G**. Now when I get myself tested and import the test result into the app I expect the status to change to **2G+**. This is however not happening, the status remains at **2G**.

## Steps to reproduce the issue

1. Go to 'Certificates' for the owner of this app.
2. The status is displayed as **2G**.
3. Import a test result for the owner of the app.
4. The status is still displayed as **2G**.

## Expected behaviour

The status is still displayed as **2G+**.

## Additional context

I have seen this feature working correctly on other people's devices. The only difference I found in the environment is that I am using my Android with *English* as system language. Might the problem be related to language settings?

## Possible fix

In the certificates my *birth date* is displayed as **Born 09/14/1970**. On the test result it's **Born Sep 14, 1970**. As far as I understand a test result is only matched to the certificates if name and birth date match. I haven't looked at the implementation, but I could imagine that the date comparison might somehow be affected by language settings.

**Comment by svenfoo** [comment] 2022-02-04 09:11
I think I asked for a test certificate with my rapid test. What I got was a link to import the result into the CWA. The result is only shown in the `Status` tab, it is not shown under `Certificates`. I didn't realize that there's actual test certificates, I have never ever received one then and I have had a lot of rapid tests done.

Yes, my name is written the same on all vaccine certificates and on the test result.

**Comment by Ein-Tim** [comment] 2022-04-19 08:46
If I understand the feature correctly this is the intended behavior. I suggest to close this issue and open an enhancement request to not only take test certificates but also test results into account for the G-Status in the https://github.com/corona-warn-app/cwa-wishlist repository.

**Comment by MikeMcC399** [comment] 2022-11-07 11:14
This issue is now obsolete, since there is no longer a legal definition or display of G-Status.

https://www.coronawarn.app/en/faq/results/#admission_policy says:

"Update on September 28, 2022:
The status proof (3G, 3G+, 2G, 2G+) is currently not relevant and therefore not shown by the app"

The issue should be closed.

**Closed** 2022-11-07 11:15 UTC
Labels: certificates, certificates-g-status, certificates-grouping

**Comment by larswmh** [comment] 2022-11-08 07:54
Dear community, 

thank you all again for contributing to this issue. See @MikeMcC399's comment above. Since the status proof is currently not relevant and therefore not shown by the app, we also think this can be closed now. Feel free to reopen or create another issue if applicable. 
Best wishes, LW

---
Corona-Warn-App Open Source Team
