### ISSUE TITLE
no option to delete test 

### ISSUE THREAD

**Issue by mdanny82** [corona-warn-app/cwa-documentation#425] opened 2020-09-13 18:06 UTC
Hello,

1. Added QR-Code to get Test-Result
2. Got Test-Result (negative in this case)
3. Forgot to delete the Test.
4. Now Test isn't available anymore
5. No option to delete the test now and add a new one.

It hangs on this screen:

![20200913_200301](https://user-images.githubusercontent.com/11460843/93025206-5384d780-f5fc-11ea-8b60-fdaf09cd27d2.jpg)

**Comment by Ein-Tim** [comment] 2020-09-13 19:00
Please see [this](https://github.com/corona-warn-app/cwa-app-android/issues/1084) Issue in the Android Repo.

**Comment by daimpi** [comment] 2020-09-13 20:20
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/1084

**Comment by abro1i** [comment] 2020-09-14 11:35
Hello @mdanny82,

thanks for your feedback.

This issue was already reported here: https://github.com/corona-warn-app/cwa-app-android/issues/1084

Best regards,
ABB

Corona-Warn-App Open Source Team

**Comment by abro1i** [comment] 2020-09-14 11:36
Duplicate of corona-warn-app/cwa-app-android#1084

**Closed by abro1i** 2020-09-14 11:36 UTC

**Comment by vaubaehn** [comment] 2020-09-16 09:23
Is there an option to delete the test on iOS version?
