### ISSUE TITLE
Anzahl der aktiven Tage wird nicht von 13 auf 14 aktualisiert.

### ISSUE THREAD

**Issue by Fruhji** [corona-warn-app/cwa-documentation#412] opened 2020-07-03 11:27 UTC
## Describe the bug

Ich benutze die App seit dem offiziellem Release und habe seitdem die Risiko-Ermittlung aktiv. Trotz diesem Zeitraum, der länger als 14 Tage ist, zeigt mir die App an, dass die App nur 13 von 14 Tagen aktiv war. Auch nach mehren Tagen warten aktualisiert sich diese Zahl nicht auf 14.

## Expected behaviour

Normalerweise sollte der Zähler nach 14 wirklich aktiven Tagen auch auf 14 aktualisert werden.

## Steps to reproduce the issue

1. Installiere die CWA-App
2. Aktiviere die Risikoermittlung
3. Lasse die Risikoermittlung mindestens 14 Tage aktiv.

## Technical details

- Mobile device: Xiaomi Mi Mix 3
- Android version: 10

---
Internal Tracking ID: EXPOSUREAPP-2238

**Comment by GPclips** [comment] 2020-08-19 08:01
Hello @user081five,

thanks for sharing the required information. I have informed our development team to assist you with that issue as soon as possible.
I also transferred the issue to the documentation repository, since this Error did occur in Android and iOS.

thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by user081five** [comment] 2020-08-20 16:54
Dear CWA Team,
The problem seems to be gone today afternoon. The status says „Risiko Ermittlung dauerhaft aktiv“ as before. I am not sure why, possibly because I have rebooted the iPhone today.
Best regards

**Comment by Ein-Tim** [comment] 2020-08-20 17:05
Related to #389

**Comment by GPclips** [comment] 2020-08-21 06:38
Hello @user081five,

thanks for your update. @Fruhji and @Ein-Tim since issue #389 has been closed, I will leave this issue #412 open. I also assigned @ChristianKienle to it, since we have talked about this issue internally. 

We will take a closer look as soon as possible to avoid the occurrence of this bug in the future.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment] 2020-09-03 09:50
Can we get an update about this? 
My active days went down to 10 again, only deactivate Bluetooth at night...
This is very confusing for the normal user @tkowark @thomasaugsten

**Comment by thomasaugsten** [comment] 2020-09-03 10:05
How you deactivate Bluetooth?
This is correct but the idea is to show you exactly how long your exposure notification was active. If you deactivate it over night then it was not active for the 14 complete days.

**Comment by Ein-Tim** [comment] 2020-09-03 10:13
I activate Flight mode.
This is technically right but imho this is just confusing for the normal user.
So or so is there any update according to this planned?

**Comment by GPclips** [comment] 2020-09-30 06:10
Hello @Ein-Tim,

sorry for the late response. Regarding https://github.com/corona-warn-app/cwa-documentation/issues/412#issuecomment-678670173: which app version is your father using and does the error still exist?

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment] 2020-09-30 20:20
@GPclips 
Yes, the App from my father now shows "Risiko-Ermittlung dauerhaft aktiv" 👍
In my own App the Days went up an up (but not really on a daily basis, more like every 2 days the App counted 1 day...).
Now I'm (again) stuck at 13 days since 1 Week.
I have the newest CWA Version installed an will report back if something changes.

**Comment by Ein-Tim** [comment] 2020-10-05 19:37
Update from my side (cc @GPclips):
Still stuck on 13 days on an iPhone XR and an iPhone 6s... Both active for more than 2 weeks...
So this bug still exists in the newer versions, any plan to fix this @thomasaugsten?

**Comment by dsarkar** [comment] 2020-11-22 11:24
Dear @Ein-Tim, is this still an issue on your phones? Thanks.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment] 2020-11-22 11:26
@dsarkar Yes it is. Stuck at 13 out of 14 days... I've also seen phones which lower the number of active days although "Risiko-Ermittlung" was active for more than 14 days...

**Comment by Ein-Tim** [comment] 2020-11-26 07:14
@dsarkar 
Updated to 1.7.1, days went down from 13 to 12... 
But since it seems like I'm an Edge Case it would be okay for me if this Issue gets closed. We can continue the discussion in https://github.com/corona-warn-app/cwa-app-ios/issues/1127 since I think this is the root cause for all this...

**Comment by dsarkar** [comment] 2020-11-26 14:28
@Ein-Tim, many thanks for the suggestions. Since this became rather inactive and on your own suggestion we will close this issue in favor of issue corona-warn-app/cwa-app-ios#1127 with the option, of course, to re-open if necessary.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Closed** 2020-11-26 14:30 UTC
Labels: UX, app android, app ios, bug, mirrored-to-jira
