### ISSUE TITLE
Linked TCN Coalition website shows now gambling/online casino? content

### ISSUE THREAD

**Issue by eliasp** [corona-warn-app/cwa-documentation#944] opened 2023-03-01 06:45 UTC
## Where to find the issue
The ["About this Project" section of README.md](https://github.com/corona-warn-app/cwa-documentation#about-this-project) .

## Describe the issue
The link to the URL https://tcn-coalition.org/ is not valid anymore, as this website just redirects via a 301 to the URL https://www.longshipbrewery.com/ which again has some kind of spammy gambling/online casino content or so.

## Suggested change
Find out whether the TCN Coalition's website changed - if so, update the URL.
If this website just isn't no more, drop the link or point to the last proper version provided by archive.org's Wayback Machine.

**Comment by MikeMcC399** [comment] 2023-03-01 07:12
@eliasp 

Thanks for spotting this link issue! Although the links are checked that they are still working, they are not checked for content, so the automatic checks didn't notice the issue!

I will submit a PR to change the link to point to the https://github.com/TCNCoalition/TCN site which contains useful information. The GitHub site also in turn links to the https://www.longshipbrewery.com/ page, however by linking in the GitHub site as much historical information as possible would still be preserved.

**Comment by MikeMcC399** [comment] 2023-03-01 07:27
- PR https://github.com/corona-warn-app/cwa-documentation/pull/945 resolves this issue

**Comment by brianebeling** [comment] 2023-03-01 13:15
Thank you @eliasp for posting this issue! I merged the change and will close the PR for now. Forwarded the observation as well.

**Closed by brianebeling** 2023-03-01 13:15 UTC
Labels: bug, documentation

**Comment by MikeMcC399** [comment] 2023-03-01 13:35
@brianebeling 

> I merged the change and will close the PR for now. 

Did you really mean "for now" i.e. you expect to something more with it later, or was that just a typo? As far as I am concerned the issue is permanently resolved. Similar things have happened in the past where organizations which were very active at the beginning of the pandemic later on ceased operations and their associated website went away, for instance https://github.com/corona-warn-app/cwa-documentation/pull/494.

**Comment by brianebeling** [comment] 2023-03-01 13:57
> Brian-J. Ebeling
> 
> > I merged the change and will close the PR for now.
> 
> Did you really mean "for now" i.e. you expect to do something more with it later, or was that just a typo? As far as I am concerned the issue is permanently resolved. Similar things have happened in the past where organizations which were very active at the beginning of the pandemic later on ceased operations and their associated website went away, for instance #494.

No, just badly worded. For me this was a first and I was a bit surprised. PR also was the wrong term, issue of course. Although.. the PR is also closed. 😄
