### ISSUE TITLE
To expensive App and Maintenance

### ISSUE THREAD

**Issue by oezguercelebi** [corona-warn-app/cwa-documentation#333] opened 2020-06-23 11:05 UTC
Yesterday I heard from my colleagues that the corona app costs 20 Million Euro and 2 Million Euro per month for the German Tax payers. Which is a ludicrous price and feels like screwing the people of Germany. I think most people wouldn’t might that the costs are high. But these numbers don’t add up in any normal way. If you understand the complexity of the app, this doesn’t make sense. SAP and Telekom are such huge companies, that they shouldn’t even charge anything and do it for free to help Germany. So many lives are affected and hit hard by the corona crises and what do they do. Let’s charge at least 50+ times the usual....

**Comment by tkowark** [comment] 2020-06-23 12:11
This is a duplicate of #224. As stated there, please use the [contact form of the Federal Government](https://www.bundesregierung.de/breg-en/service/contact) for such questions.

Mit freundlichen Grüßen / Best regards,
TK
Corona-Warn-App Open Source Team

**Closed by tkowark** 2020-06-23 12:11 UTC
Labels: duplicate

**Comment by sventuerpe** [comment] 2020-06-23 14:29
@oezguercelebi For comparison, our government spends twice the development cost of CWA to support the [distribution of subscription newspapers](https://www.br.de/nachrichten/bayern/zeitungsverlage-hoffen-aus-foerdergelder-aus-berlin,RwD0Hln) and by _newspapers_ they mean actual stacks of paper onto which yesterday’s Internet news have been printed.

**Comment by oezguercelebi** [comment] 2020-06-23 15:20
> @oezguercelebi For comparison, our government spends twice the development cost of CWA to support the [distribution of subscription newspapers](https://www.br.de/nachrichten/bayern/zeitungsverlage-hoffen-aus-foerdergelder-aus-berlin,RwD0Hln) and by _newspapers_ they mean actual stacks of paper onto which yesterday’s Internet news have been printed.

Seems normal to me. Because we have a lot of elder people that don’t understand the thing called the internet. Government is spending anyway to much left and right. But this case involves techies, that don’t like bullshitting people.
