### ISSUE TITLE
Risk explanation is given as "increased" even with a low risk level

### ISSUE THREAD

**Issue by niels** [corona-warn-app/cwa-documentation#405] opened 2020-08-11 14:25 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

On the "Your Risk Status" screen, a green card with "Low Risk" is shown at the top. However, the last paragraph in the bottom "Risk of Infection" card reads (emphasis added):

> **Therefore, your risk of infection has been ranked as increased.** Your risk of infection is calculated from the exposure logging data (duration and proximity) locally on your device. Your risk of infection cannot be seen by, or passed on to, anyone else. When you get home, please also **avoid close contact with members of your family or household**.

This seems to contradict the actual "low risk" rating and is thus confusing. 

The Android app seems to display the `risk_details_information_body_notice` string, the wording of which seems to be specific to an increased risk, irrespective of the actual risk rating.

The iOS App stores this text under the more specific `ExposureDetection_Explanation_Text_High` key which only seems to be displayed when the risk rating is actually high.

## Expected behaviour

When the top "Your Risk Status" section shows "Low Risk", the "Risk of Infection" section should not mention an "increased" risk, nor recommend avoiding contact with household members.

When the "Risk of Infection" section describes an "increased" risk or recommends avoiding contact with household members, the top "Your Risk Status" section should show "Increased Risk".

## Steps to reproduce the issue

Given that you have no recorded risk contacts,

1. Open the app.
2. Click on "Low Risk".
3. Observe the contrast in verbiage between the topmost "Your Risk Status" card (with a green background) and the last paragraph in the bottommost "Risk of Infection" card (dark grey background).

![Wire 2020-08-11 at 4_20 PM](https://user-images.githubusercontent.com/16709/89908881-fc937900-dbdd-11ea-803d-a816745876fd.png)
![Wire 2020-08-11 at 4_20 PM2](https://user-images.githubusercontent.com/16709/89908886-fef5d300-dbdd-11ea-99cd-6123d10cf5cd.png)

## Technical details

- Mobile device: Nokia 6.1
- Android version: 10
- App version: 1.2.0

## Possible Fix

Show different `risk_details_information_body_notice`s depending on the actual risk level.

## Additional context

n/a

---
Internal Tracking ID: EXPOSUREAPP-2191

**Comment by GPclips** [comment] 2020-08-12 12:44
Hello @niels,

I have informed our development team to check your issue.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment] 2020-08-12 16:55
@vaubaehn 
kindly cross-referenced this to https://github.com/corona-warn-app/cwa-app-android/issues/1006 and pointed out there that the issue is fixed in https://github.com/corona-warn-app/cwa-app-android/pull/1004

There seem to be two different Internal Tracking IDs used though:
This issue (https://github.com/corona-warn-app/cwa-documentation/issues/405) refers to EXPOSUREAPP-2191 whereas the PR
https://github.com/corona-warn-app/cwa-app-android/pull/1004 refers to EXPOSUREAPP-2171
So perhaps there was a typo in one of those IDs?

**Comment by MikeMcC399** [comment] 2020-08-13 17:09
CWA 1.2.1 is now available on Google Play Store. I've installed it and confirmed that this issue is fixed.

**Comment by MikeMcC399** [comment] 2020-08-20 07:54
@GPclips & @JoachimFritsch 
I believe this issue could be closed.

**Comment by daimpi** [comment] 2020-08-20 11:43
Did this actually ever affect iOS? I was just assuming so b/c of the [tweet](https://twitter.com/gentlemanrajue/status/1293298429234499584) mentioned above. If so: has this also been fixed for iOS? :)

**Comment by svengabr** [comment] 2020-09-10 13:14
We got an official statement from the Robert Koch Institute:

**German**
>Als Herausgeber der Corona-Warn-App bedankt sich das Robert Koch-Institut für die vielen Rückmeldungen zur Risikostatusanzeige auf dem HomeScreen. Diesem Dank schließen wir uns als Entwicklerteam der App an. Nach Abwägung aller Argumente und in Abstimmung mit dem Bundesministerium für Gesundheit hat das RKI entschieden, die zweistufige Risikodarstellung (grün und rot) beizubehalten.

>Die App muss möglichst einfach und allgemeinverständlich in der Anwendung sein. Durch die Unterscheidung von niedrigem und erhöhtem Risiko können den Nutzerinnen und Nutzern auf ihren Risikostatus abgestimmte Handlungsempfehlungen gegeben werden. Die zusätzliche Anzeige von Begegnungen, die bestimmte Kriterien erfüllen, erhöht die Transparenz. Für alle diejenigen, die sich mit der Risikobewertung und ihren Parametern eingehender beschäftigen möchten, haben RKI und Entwicklerteam detaillierte Beschreibungen auf GitHub zur Verfügung gestellt.

>Die Texte in der Corona-Warn-App werden wir unter Berücksichtigung Ihres Feedbacks weiter anpassen. Mit einem anstehenden Update werden wir weitere Erläuterungen zum besseren Verständnis der angezeigten Risikobegegnungen geben. Zudem wird geprüft, ob mit einem späteren Update eine Risikobegegnungshistorie in der App dargestellt werden kann.

>Auch zukünftig werden wir Anregungen und Vorschläge zur Verbesserung der Corona-Warn-App aufgreifen, diskutieren und, soweit sinnvoll und möglich, umsetzen. Wir freuen uns, wenn Sie sich weiter mit konstruktivem Feedback beteiligen.

---

**English**
>As the publisher of the Corona-Warn-App, the Robert Koch-Institute as well as the development team would like to thank you for the many feedbacks on the risk status display on the HomeScreen. After weighing up all arguments and in coordination with the Federal Ministry of Health, the RKI has decided to keep the two-level risk display (green and red).

>The app must be as simple and generally understandable as possible in its application. By differentiating between low and increased risk, users can be given recommendations for action based on their risk status. The additional display of encounters that meet certain criteria increases transparency. For those who want to take a closer look at risk assessment and its parameters, RKI and the development team have provided detailed descriptions on GitHub.

>We will further improve the texts in the Corona-Warn-App and we will continue to listen for feedback of the community. With an upcoming update, we will provide further explanations to help you better understand the risk encounters displayed. In addition, we will check whether a later update will allow a risk encounter history to be displayed in the app.

>In the future, we will continue to take up, discuss and, where reasonable and possible, implement suggestions and proposals for improving the Corona Warning App. We would be pleased if you continue to contribute with constructive feedback.

Further text improvements are being introduced in the upcoming hotfix release 1.3.1.

RC1 of 1.3.1 is already available:
https://github.com/corona-warn-app/cwa-app-android/releases/tag/1.3.1-SNAPSHOT-RC1
https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.3.1-RC1

Since the decision from the RKI is final, I will close this issue now.

Best regards,
SG

Corona-Warn-App Open Source Team

**Closed by svengabr** 2020-09-10 13:14 UTC
Labels: app, bug, documentation, mirrored-to-jira

**Comment by MikeMcC399** [comment] 2020-09-10 14:16
@svengabr 
It's good to read the feedback from RKI regarding the strategy for green and red status. It's very timely for me personally because for the first time today I got "1 exposure with low risk" and I'm wondering what I should think and do about that!

[Risk explanation is given as "increased" even with a low risk level](https://github.com/corona-warn-app/cwa-documentation/issues/405) https://github.com/corona-warn-app/cwa-documentation/issues/405 was actually about a bug where the risk status said "No exposure up to now" and then said, for no reason, "... your risk of infection has been ranked as increased.", which was inconsistent and made no sense. In any case the problem behind https://github.com/corona-warn-app/cwa-documentation/issues/405 was fixed in CWA Android 1.2.1, so it is good for this issue to be closed.
