### ISSUE TITLE
rapid test profile bad usability / Schnelltest-Profil Erstellung schlechte Usability

### ISSUE THREAD

**Issue by Marc-Boerner** [corona-warn-app/cwa-documentation#613] opened 2021-05-15 08:38 UTC
Bei der Erstellung des Schnelltestprofil kann bereits nur nach Eingabe eines Vornamens gespeichert werden.
Außerdem kommt man unter IOS sehr schlecht aus der Geburtstagseingabe, da über der Datumsauswahl groß der "Speichern" Button erscheint, wodurch direkt ein QR Code erstellt wird.

---
Internal Tracking ID: [EXPOSUREAPP-7294](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7294) rapid test profile - no verification for captured data + no check if required fields are filled
Internal Tracking ID: [EXPOSUREAPP-7290](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7290)   rapid test profile - misleading button when capturing date of birth

**Comment by dsarkar** [comment] 2021-05-15 08:45
@Marc-Boerner Danke für den report. Internal Tracking ID: [EXPOSUREAPP-7294](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7294)

**Comment by Ein-Tim** [comment] 2021-05-15 08:48
Es scheint beabsichtigt zu sein das man nur den Vornamen speichern kann, siehe den Text in der App der beim ersten mal auftaucht wenn man das Schnelltest-Profil öffnet:
<img src="https://user-images.githubusercontent.com/67682506/118354303-c4ed9f00-b56a-11eb-9547-34233ddd9c65.jpg" width="300">

Das es kompliziert ist bei iOS nach der Geburtsdatumseingabe weiter zu machen stimmt, das ist ein guter Punkt!

**Comment by Ein-Tim** [comment] 2021-05-15 08:49
@dsarkar 

I suggest to change the title because there are no required fields, see my comment above

**Comment by dsarkar** [comment] 2021-05-15 08:52
@Ein-Tim Thanks for point that out.

**Comment by dsarkar** [comment] 2021-05-15 08:54
@Ein-Tim @Marc-Boerner The **Speichern** Button is a  bit misleading when one selects DoB, right?

**Comment by Ein-Tim** [comment] 2021-05-15 08:55
@dsarkar 

Yes because one things that you save your birthday but instead you safe the whole profile...

**Comment by dsarkar** [comment] 2021-05-15 08:58
@Ein-Tim Ok, agreed, do you want to open a separate issue for the **SPEICHERN** / DoB issue?

**Comment by dsarkar** [comment] 2021-05-15 09:00
@Ein-Tim Do we have already and issue on verification of DoB?

**Comment by Ein-Tim** [comment] 2021-05-15 09:59
@dsarkar We have https://github.com/corona-warn-app/cwa-app-ios/issues/2688 reg. the possibility to set the date in the future.

**Comment by Ein-Tim** [comment] 2022-04-18 13:22
@dsarkar This meanwhile got an iOS exclusive issue, as all other points was addressed.

The problem is the "Speichern" button, which looks like it saves the date of birth but actually saves the whole profile.

Two ways to proceed here:
1. Close this issue & I create a new issue reg. the "Speichern" button in the iOS repo
2. Transfer this issue to the iOS repo.

**Comment by MikeMcC399** [comment] 2022-05-16 18:29
Under CWA Android 2.22.1 there are no required fields in the Rapid Test Profile. A user is able to populate each field or leave it blank as they wish. As @Ein-Tim mentioned in https://github.com/corona-warn-app/cwa-documentation/issues/613#issuecomment-841624642, this corresponds to the help information (three-dot symbol) > Information.     

From `rat_profile_onboarding_card_consent3`::

"_At a testing point, you can then have your rapid test profile’s QR code scanned as a means of quickly and securely providing your data to the testing point. The testing point will need your data to carry out the test. However, you do not need the app to provide your data. You decide yourself which data is included in the QR code, and which information you communicate to the testing point by other means._"


Under Android, the date-picker offers an OK button to save the Date of Birth. This does not save the whole profile.

@Ein-Tim 
Would you like to create a new iOS issue for the Save button (as you suggested in alternative 1.)? Then this issue could be closed.

**Comment by dsarkar** [comment] 2022-05-17 10:37
@Marc-Boerner Thanks for reporting, see the above comments https://github.com/corona-warn-app/cwa-documentation/issues/613#issuecomment-1101405247 and https://github.com/corona-warn-app/cwa-documentation/issues/613#issuecomment-1127998122. We will close this is issue therefore. 

@Ein-Tim @MikeMcC399 Thanks for the analysis. @Ein-Tim Feel free to open a new issue in the iOS repo.


Best wishes, DS

---
Corona-Warn-App Open Source Team

**Closed by dsarkar** 2022-05-17 10:37 UTC
Labels: bug, UX, mirrored-to-jira, rapid-test

**Comment by dsarkar** [comment] 2022-05-17 10:39
@MikeMcC399 @Ein-Tim FYI - Internal Tracking ID: [EXPOSUREAPP-7290](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7290) deals with [iOS] RAT profile - misleading button when capturing date of birth

**Comment by Ein-Tim** [comment] 2022-05-17 15:25
@dsarkar Thanks, I'll open an issue later so that we have an issue here on GitHub. I'll add the JIRA ticket myself.

**Comment by Ein-Tim** [comment] 2022-05-21 19:09
Issue opened: https://github.com/corona-warn-app/cwa-app-ios/issues/4570
