### ISSUE TITLE
App shows "1 exposure with low risk", this is contradictory to the defnition under "Overview"

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#416] opened 2020-08-26 14:14 UTC
## Where to find the issue
In the App when you had a "Low-Risk Exposure".

## Describe the issue & Suggested change

- in German the App shows "1 **Risiko**-Begegnung mit **niedrigem Risiko**", that is contradictory ("Risiko-Begegnung mit niedrigem Risiko" makes no sense) to the definiton of "Risiko-Begegnung", so it should be canged to: "1 Begegnung mit niedrigem Risiko".
 
- in English the App shows "1 exposure with low risk", this is also contradictory to the defnition of Exposures in the Overview of the App and should be changed to "1 encounter with low risk".

This was also already mentioned by @benzman81 [here](https://github.com/corona-warn-app/cwa-backlog/issues/23#issuecomment-652661721).

**Comment by mf179** [comment] 2020-08-27 12:55
Thanks for distributing the issues identified under #23 to a few separate and therefore better managable issues. For this one here  I don´t like the removal of the german part of the initially proposed heading as the quoted german statement is weird. It is as you probably copied from somewhere: "it makes no sense to state "Risikobegegnung mit niedrigem Risiko"".

Correcting it as proposed (change on main CWA screen Risikobegegnung to Begegnung) would be in my view a user interface change ? As proposed under "Bad UX. "Risiko Begegungen" are not reflected in the "Risiko Status" wishlist#113"
Of course, it requires also documentation update, if the CWA screen "Überblick" is considered as documentation and not UX.

Given that the FAQ declares the "Risikobegegnung mit niedrigem Risiko" as being harmless  https://www.coronawarn.app/en/faq/#encounter_but_green  (oder als "werden als unbedenklich verworfen" in den deutschen FAQ). I wouldn´t use the word risk at all in this statement an the green main screen. It should  rather read "1 nicht infektionsrelevante Begegnung mit einem positiv Getesteten". 

However, I would suggest to solve the issue here not on its own, but in the context of what "App risk status screen: misleading wording wishlist#121" describes as a problem. The issue is: in the absence of known, really risky exposures the App can´t make any reasonable assumption about any overall risk.
For someone living in total isolation the app claims "low overall risk", although there is none.
For someone with daily close contact to infected people who don´t use the app the app also claims "low overall risk".

The "green status" would need to be explained that it is just the app that cannot determine a risk as there are no exposures recoreded that are known to be an infection risk. And that this still doesn´t exclude that the user got in contact with infected people, e.g. as not everybody uses the app. The current App makes a general overall "no-risk" statement so that user may wrongly assume he is save in what he did so far.

I would suggest to open an (backlog?) issue on the bigger "green status" problem.

**Comment by svengabr** [comment] 2020-08-27 14:51
@Ein-Tim please have a look at this particular comment:
https://github.com/corona-warn-app/cwa-backlog/issues/23#issuecomment-681949119

> Hi everyone,
> 
> I can give you some insights what is going on right now regarding this topic.
> 
> A proposal was made to introduce a third color besides red and green but finally dismissed by the RKI to avoid confusion.
> So red and green will remain the only two colors as a state for risk encounters.
> However, an upcoming update will add more information for the users regarding Low-Risk-Encounters.
> 
> The final texts are being reviewed and translated for the app localizations at the moment.
> 
> I agree with @mf179 to close this issue here. Lets continue the discussion in the related issues if required.
> 
> Best regards,
> 
> ABB
> 
> Corona-Warn-App Open Source Team

If I understood correctly, this will already fix the issue you are mentioning, right?

**Comment by Ein-Tim** [comment] 2020-08-27 15:28
@svengabr 

Yeah, more Infos are good (btw, can you specify "more information" a little bit?), 
but the point of this Issue is that whats shown to the users, when thy had a "Low-Risk encounter" ("1 **exposure** with low risk),  is contradictory to the definiton of "**Exposures**" ("Encounters over an extended period and in close proximity to a person diagnosed with COVID-19") under the point "Overview" in the App. 
And even worse is that in German is shown "**1 "Risiko**-Begegnung mit niedrigem **Risiko**", that just makes logically no sense.

**Comment by daimpi** [comment] 2020-08-27 17:36
Just found this issue which seems to hit on a similar point: https://github.com/corona-warn-app/cwa-wishlist/issues/148

I guess those two issues could be merged and progress tracked in just one of them.

**Comment by Ein-Tim** [comment] 2020-08-27 18:08
Yes, @daimpi I think this issue should be still tracked in the Backlog, because I don't think that removing the confusing definition is something for the wishlist, or?

**Comment by Ein-Tim** [comment] 2020-08-27 18:11
Oh, @GPclips clips transferred the other issue from the iOS Repo to the Wishlist...
@GPclips could you give your opinion to that? The correction of a wrong definition is (imho) not something for the wishlist...

**Comment by daimpi** [comment] 2020-08-27 18:15
I'd also think that the documentation repo would be right place, but I don't have strong feelings either way tbh 😄.

**Comment by mf179** [comment] 2020-08-28 07:11
Svengabr, the issue here is not about "more info". The screens of the CWA share misleading information. So there is no real need for adding more, but for correction.

Again, "1 Risikobegegnung mit niedrigem Risisko" contradicts the FAQ. I would consider this even a wrong statement. According to the FAQ there is no risk at all. And the description screen for the "risk statement: green status" is also not correct.

Furthermore a number of the statements in the screens "Risiko-Ermittlung" and "Überblick" share misleading or contradicting information. A good, but long description is under "App-Information" -> "Datenschutz" where I wouldn´t have expected it. The infos and terms shared by the screens should be aligned to this. This is why I asked under #23 whether you share the new screens under work somewhere for review.

I have no strong feeling under what category this worked on. It should just be avoided that it falls through the cracks. I.e. that it is not worked on as the info shared by the CWA screens seems not coverred by scope described for the "documentation repository".

**Comment by tkowark** [comment] 2020-08-28 07:20
Documentation is actually the right place for *bugs* in screens and texts of both apps. That's why issues that affect general texts are moved from the ios / android repos to documentation on a regular basis. Things that could be improved but are not factually wrong are moved to wishlist. 

This whole thing is not falling through the cracks but actively being worked on. I'll discuss sharing preliminary versions with the team.

**Comment by mf179** [comment] 2020-08-28 07:42
Thanks for the explanation.
As it might take some time until preliminary versions are shared let me suggest a modification of the screens:

On the green main screen "n Risikobegegnungen mit niedrigem Risiko" should be changed to "n unbedenkliche Begegnungen" in line with the FAQ.

Further on the green main screen there shouldn´t be any risk statement. So "Niedriges Risiko" should be changed to "Status grün".

The klick on the related main screen link should explain the "Status grün" as:
"Ihr Status ist grün da bisher alle aufgezeichneten Begegnungen als unbedenklich erachtet werden.
 Etwaig angezeigte "unbedenkliche Begegnungen" waren nur kurz oder mit größerem Abstand und daher unbedenklich.
Es kann jedoch nicht ausgeschlossen werden, daß ein Infektionsrisiko bestand, da z.B. nicht jeder die CWA benutzt.
Daher sollten sie in jedem Falle die Hygieneregeln befolgen. Auflistung derer."

Can we change the issue title to "clarification of the risk statements for green status" ?

**Comment by abro1i** [comment] 2020-08-28 11:59
Hi @mf179,

i have added images here:

https://github.com/corona-warn-app/cwa-backlog/issues/23#issuecomment-682485410

Best regards, 

ABB 

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment] 2020-08-28 13:07
With the [updated Texts](https://github.com/corona-warn-app/cwa-backlog/issues/23#issuecomment-682485410)this problem would be solved, I will leave this issue open until it's finally released 👍

**Comment by mf179** [comment] 2020-08-29 10:06
Thanks ABB.
The images shared under backlog#23 can still be understood as a claim of a low overall risk, which may make the user feel safe although he not necessarily is.
As correctly stated in the shared images, the app analyses only what the app knows.
It cannot know about any potential really risky encounters with people not using the app, i.e. outside the app.
At least a disclaimer is missing that the app cannot exclude a more serious infection risk even if it is claiming "low [overall] risk".

**Comment by daimpi** [comment] 2020-08-29 11:10
@mf179 the FAQ entry regarding green exposures is currently being reworked: https://github.com/corona-warn-app/cwa-website/issues/307.
Regrading the fact that the app can only analyze what it knows, this is being discussed here: https://github.com/corona-warn-app/cwa-wishlist/issues/110
🙂

**Comment by mf179** [comment] 2020-08-30 07:08
Thanks daimpi.

You state under https://github.com/corona-warn-app/cwa-website/issues/307 why it isn´t possible to determine a confidence for the "low [overall] risk". And for the same reasons I fully support slobentanzers proposed removal of the green risk statement. Make it "green status" to avoid any risk claims that you can´t back.

I have no major problem with the german FAQ entry (besides some ambiguity needs to be removed about what the discarding means). But the intended statement is correct in the sense that the "no/low risk encounters" don´t pose any risk. So I mentioned the contradition to show that the FAQ states that the "green risk encounters" are no risk.

I don´t agree that wishlist#100 covers the problem. As we learned here, wishlist is for something nice to have. So wishlist#100 is categorized and treated as an additional "feature", i.e. providing a confidence statement. Stating about low risk although the actual risk cannot be determined is a bug. This needs to be fixed in the app screens and not the FAQ. This is why I proposed to clarify the issue here accordingly.

To avoid confusion, I like that the app shows the "unbedenklichen Begegnungen mit positiv-Getesteten". But this is only good for demonstrating that the app works and perhaps good for raising awareness.

It is stated in a few places that the app/makers don´t want to scare the user. So avoid using the word risk everywhere where you have no confidence about any risk. It should be not difficult to describe the overall situation without the word risk. Then you also don´t need to tell the user in the "green risk explanation" "don´t be afraid" as in the newly proposed screens shared by ABB.

**Comment by mtb77** [comment] 2020-08-30 08:00
Hi,

please see also the comment from @GisoSchroederSAP here: https://github.com/corona-warn-app/cwa-wishlist/issues/110#issuecomment-683357784 

We do now have three different Issues open that are basically discussing slightly the same aspects:
- this one
- https://github.com/corona-warn-app/cwa-backlog/issues/23
- https://github.com/corona-warn-app/cwa-wishlist/issues/110

Agreed that I will close this one in favor of the others?

 Sascha

 Corona-Warn-App Open Source Team

**Comment by mf179** [comment] 2020-08-30 09:40
Hi Sascha,

Ein-Tim opened this issue here as the people vocal on backlog#23 want to use it for getting more details per separate "low-risk-encounter".

This here can be closed, if backlog#23 clarifies that it intends to clarify the "green overall low risk statement". It should be noted that lack of confidence is the same problem for "green low risk" without any "low-risk-encounter".
Alternatively, wishlist#110 becomes a documentation-issue and should clarify the target of clarifying the green risk statement.

Currently wishlist#110 requests a feature that shows a "confidence-score". 
It is however as daimpi and GisoSchroederSAP state: it is rather not possible to determine such a score. There are more examples why not.
So wishlist#110 will be closed as a feature request as such a feature is not suitable/possible.

Without clarifying and/or changing the referenced issue category/target there seems no other issue covering the problem properly. From that it shouldn´t be closed.

**Comment by Ein-Tim** [comment] 2020-08-30 09:47
@mtb77 
For me it would be ok to close this issue, if the [texts](https://github.com/corona-warn-app/cwa-backlog/issues/23#issuecomment-682485410) are released like this, I'm happy and the problem is solved.

**Comment by mtb77** [comment] 2020-08-30 12:34
Thanks @Ein-Tim , Wilco :) 

Sascha

Corona-Warn-App Open Source Team

**Comment by mf179** [comment] 2020-08-31 08:36
Hi Sascha,

I commented this already all under # 23. However backlog#23 has no clear issue description, which obviously prevents a focused discussion there. The opening of this issue # 416 here was the only sensible reply to my proposal clarifying what issue # 23 is about.

As long as # 23 is not clear that it covers the issue here there is no justification for closing it.
A clarification from the CWA Open Source Team that it will be coverred there would be an acceptable justification.

As already mentioned under backlog#23, the text of the shared draft screen still contradicts the presumably correct FAQ:
draft ("Begegnung mit mit niedrigem Risiko") -- FAQ ("unbedenkliche Begegnung"). I.e. it is not appropriate to call it "low risk".

Another "risk statement issue" relates to wishlist # 110. # 110 backs why the the shared green draft screen should not state "low overall risk. Just that # 110 will probably not solve it.

**Comment by Ein-Tim** [comment] 2020-08-31 09:00
@mf179 

I think it is okay to close this issue because this Issue is about:
> App shows "1 exposure with low risk", this is contradictory to the defnition under "Overview"

This is fixed with the screenshots @abro1i shared and for all other Issues you have I beg you to open another Issue. This would be very helpful imho. Thanks

**Comment by abro1i** [comment] 2020-08-31 09:08
> This is fixed with the screenshots @abro1i shared and for all the other things you have, I beg you to open another Issues. This would be very helpful imho. Thanks

I agree, lets keep this ticket here closed. Thanks everyone!

Best regards, 

ABB 

Corona-Warn-App Open Source Team

**Comment by mf179** [comment] 2020-08-31 09:16
this comment from cfritsche caused the reopening of backlog# 23:
"Until now the backlog repo was the place to track what is being worked on. So this issue is not just overlapping with others, this issue should be about what is in development. Normally these issues are closed when the feature is available. Are you handling this differently now?"

Sharing some drafts makes nothing available.

**Comment by Ein-Tim** [comment] 2020-08-31 09:19
@mf179 
Yes, but here we are in the Documentation repo and you're right sharing Screenshots makes nothing available, but this will be released (in v. 1.3 I guess?) and if not we can reopen this.
Cheers

**Comment by mf179** [comment] 2020-08-31 09:23
Also documentation issues can only be considered solved, if the officially released documention doesn´t include it.

**Comment by Ein-Tim** [comment] 2020-08-31 09:25
So you want to reopen it to discuss what? 🙂

**Comment by mf179** [comment] 2020-08-31 09:32
It doesn´t relate to any discussion. A ticket can be closed, when the issue is solved.
With your logic you can close all issues and say, please reopen, if not solved by v.1.3.  Where you also just guess that it will be in there.

**Comment by Ein-Tim** [comment] 2020-08-31 09:35
Ok, I can't reopen it, @mtb77 Whats your opinion to this?

**Comment by daimpi** [comment] 2020-08-31 14:32
I'd in general agree, that an issue should probably stay open at least until a resolving PR is merged. But maybe those changes which we see in the screenshots have actually been merged already? If so, it would be good to get a link to the PR 🙂. 

Regarding the other issues and how I think they relate to this one here: 
- https://github.com/corona-warn-app/cwa-backlog/issues/23 is imho not just about "changes of texts" but rather also entails "changes of information available to the user" like requested in https://github.com/corona-warn-app/cwa-wishlist/issues/100 and has therefore only some overlap with this issue here.
- https://github.com/corona-warn-app/cwa-wishlist/issues/110 is also a separate discussion which touches on points which are on a much more fundamental level than the changes proposed here.
- I think the most overlap actually exists with https://github.com/corona-warn-app/cwa-wishlist/issues/148 which seems to be almost identical to this issue here (and which probably should also be closed once the changes have been implemented).

**Comment by mf179** [comment] 2020-08-31 16:43
Daimpi, I think we all know very well that the wishlist is for "new features", i.e. something not really necessary for the main service of the CWA and also not correcting any bugs. So it is no surprise that those items get typically no priority. So it requires obviously a non-wishlist issue for solving those risk statement issues within a reasonable timeframe. Let´s see whether and how the "overall risk statement issue" progresses under wishlist # 110.

It seems also obvious that backlog# 23 got highjacked for working on wishlist# 100, just picking "more information for the end users" from the issue description. And there is hardly any focus on other parts of the issue description: ""1 Risiko-Begegnung" but the screen says "Niedriges Risiko". I didnt find information, what this exactly means ".

Thanks for your effort. To me it is however not helpful to search for more wishlist issues that might cover it. It needs obviously a documentation issue for resolving the risk statement issues. For me it is also no longer a "definition problem". As proposed before, the "[Risiko-]Begegnung mit niedrigem Risiko" should be changed to "unbedenkliche Begegnung". And the explanation screen for the green status/risk explains what this is. So it doesn´t need any definition. 

I will wait a bit and see in what direction wishlist # 110 moves and open a documentation issue, if needed.

**Comment by Ein-Tim** [comment] 2020-08-31 16:49
Again, I don't think that the "Low-Risk Encounters" are 100% harmless.
With the Information I have, it would be wrong and very dangerous to tell the user that every "Low-Risk Encounter" was harmless.

**Comment by Ein-Tim** [comment] 2020-09-04 09:13
@abro1i 

Are [these Texts](https://github.com/corona-warn-app/cwa-backlog/issues/23#issuecomment-682485410) now released with 1.3.0?

**Comment by Ein-Tim** [comment] 2020-09-07 10:59
@mtb77 @svengabr 
Please reopen this Issue since the Texts are **not** released with v. 1.3.0.
This Issue should stay open until the texts are released.
Thank you

**Comment by svengabr** [comment] 2020-09-11 09:10
We got an official statement from the Robert Koch Institute:

**German**
>Als Herausgeber der Corona-Warn-App bedankt sich das Robert Koch-Institut für die vielen Rückmeldungen zur Risikostatusanzeige auf dem HomeScreen. Diesem Dank schließen wir uns als Entwicklerteam der App an. Nach Abwägung aller Argumente und in Abstimmung mit dem Bundesministerium für Gesundheit hat das RKI entschieden, die zweistufige Risikodarstellung (grün und rot) beizubehalten.

>Die App muss möglichst einfach und allgemeinverständlich in der Anwendung sein. Durch die Unterscheidung von niedrigem und erhöhtem Risiko können den Nutzerinnen und Nutzern auf ihren Risikostatus abgestimmte Handlungsempfehlungen gegeben werden. Die zusätzliche Anzeige von Begegnungen, die bestimmte Kriterien erfüllen, erhöht die Transparenz. Für alle diejenigen, die sich mit der Risikobewertung und ihren Parametern eingehender beschäftigen möchten, haben RKI und Entwicklerteam detaillierte Beschreibungen auf GitHub zur Verfügung gestellt.

>Die Texte in der Corona-Warn-App werden wir unter Berücksichtigung Ihres Feedbacks weiter anpassen. Mit einem anstehenden Update werden wir weitere Erläuterungen zum besseren Verständnis der angezeigten Risikobegegnungen geben. Zudem wird geprüft, ob mit einem späteren Update eine Risikobegegnungshistorie in der App dargestellt werden kann.

>Auch zukünftig werden wir Anregungen und Vorschläge zur Verbesserung der Corona-Warn-App aufgreifen, diskutieren und, soweit sinnvoll und möglich, umsetzen. Wir freuen uns, wenn Sie sich weiter mit konstruktivem Feedback beteiligen.

---

**English**
>As the publisher of the Corona-Warn-App, the Robert Koch-Institute as well as the development team would like to thank you for the many feedbacks on the risk status display on the HomeScreen. After weighing up all arguments and in coordination with the Federal Ministry of Health, the RKI has decided to keep the two-level risk display (green and red).

>The app must be as simple and generally understandable as possible in its application. By differentiating between low and increased risk, users can be given recommendations for action based on their risk status. The additional display of encounters that meet certain criteria increases transparency. For those who want to take a closer look at risk assessment and its parameters, RKI and the development team have provided detailed descriptions on GitHub.

>We will further improve the texts in the Corona-Warn-App and we will continue to listen for feedback of the community. With an upcoming update, we will provide further explanations to help you better understand the risk encounters displayed. In addition, we will check whether a later update will allow a risk encounter history to be displayed in the app.

>In the future, we will continue to take up, discuss and, where reasonable and possible, implement suggestions and proposals for improving the Corona Warning App. We would be pleased if you continue to contribute with constructive feedback.

Further text improvements are being introduced in the upcoming hotfix release 1.3.1.

RC1 of 1.3.1 is already available:
https://github.com/corona-warn-app/cwa-app-android/releases/tag/1.3.1-SNAPSHOT-RC1
https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.3.1-RC1

Since the decision from the RKI is final, I will close this issue now.

Best regards,
SG

Corona-Warn-App Open Source Team

**Closed by svengabr** 2020-09-11 09:10 UTC
Labels: bug, documentation

**Comment by Ein-Tim** [comment] 2020-10-05 16:40
Just a quick update for everybody:
These changes are now finally released with Version 1.3.1/1.3.2...
